### ISSUE TITLE
Mobile 上的語言選擇欄

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#100]
讓它不要跳…

好像知道怎麼修，總之先記著。

**Comment by flywindy** [comment]
我記得我們前幾天討論是說直接用 CSS 解？ex: `hidden-xs`
如果是的話讓 @starwilly 弄吧？

**Comment by uranusjr** [comment]
應該是要用 CSS 解比較好，我之前有跟他嘴砲一個做法是根據螢幕大小選擇要用 `nav-right` 或 `nav-left`。不過不管用什麼做法還是要他做，因為我不是很懂現在到底是怎麼做出來的。XD

**Comment by ccwang002** [comment]
我發現選單在做動畫的時候，會有 .collapsing 這個 class 也許可以用用看

**Comment by ccwang002** [comment]
... 當我沒說

**Comment by starwilly** [comment]
TP 說的那個方法感覺可行，我之後弄弄看吧

**Comment by starwilly** [comment]
我調了 lang-dropdown 的位置，讓它不會突然跳動，不過我設定的 css 動畫在手機版 safari 沒作用，有人可以幫忙看一下嗎XD
--> `mobile-nav` branch

**Comment by uranusjr** [comment]
真的耶好神奇，不過完全看不出來有什麼問題… 我直接把那個 animation 抽出來試了一下也正常，目前只能判斷可能是它和 jQuery 那個 menu 捲下來的效果合在一起的問題。沒什麼頭緒。

BTW 那個動畫的時間點好像有點怪。是否應該在 collapsing 的時候就一起 fade in 才對，而不是等 menu 顯示完之後才接著開始？

**Comment by uranusjr** [comment]
Closing since we’re freezing features for 2016.
