### ISSUE TITLE
Transifex 整合

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#103]
除了自動 push 以外應該也要可以自動 pull，每次都要手動更新 master 實在太笨。

理想的方法應該是做在 Travis 上面，在某些 push 時自動執行 tx pull、compile 後 commit、push 回 GitHub。這個 push 可以加上 [`[ci skip]`](https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build) 來避免觸發下一個 Travis build。

**Comment by flywindy** [comment]
啊 這裡不能點讚～給你個讚！
