### ISSUE TITLE
Chromium 開 incognito mode 下修改使用者資料。

### ISSUE THREAD

**Issue by xingularity** [pycontw/pycontw2016#114]
如果我發現如果要註冊新的使用者，當輸入完帳號密碼之後到「修改使用者資料」畫面下，如果 chromium 是開在 incognito mode，你修改完使用資料之後按下送出會回到登入的帳號密碼畫面，重登入之後剛剛的修改都不見了，一切重來。

**Comment by uranusjr** [comment]
我無法重現這個問題 (Chromium 50.0.2638.0 on OS X)，可以給一些額外資訊嗎？例如是否有 email 認證完畢、是否原本已經有編輯成功的資料（有哪些）、修改了哪些欄位等等。
