### ISSUE TITLE
[Proposal Form] 欄位字數限制考慮中英用字數差異

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#123]
目前最有感的是 abstract 欄位。

### 現在狀況

Abstract 限制 500 字時，中文沒問題，但英文會有點受限（不到 100 words）。

- `This is a book.` 15 chars
- `這是一本書。` 6 chars

同樣的意思，可能英文會占用比較多的 unicode 字元數。

### 建議改良

有個折衷的辦法，使用 [`unicodedata.east_asian_width`](https://docs.python.org/3.4/library/unicodedata.html#unicodedata.east_asian_width) 把全型字當成 2 單位。

實作：

```py
# real_width.py
from unicodedata import east_asian_width

to_width = {'Na': 1, 'W': 2, 'F': 2}
def count(s):
    return sum(to_width[east_asian_width(c)] for c in s)
```

```python
# python3 -i real_with.py
>>> count('This is a book.')
15
>>> count('這是一本書。')
12
```

### 待解決問題

前端驗証，我不知道怎麼在 javascript 實作上述的功能，這樣 counter 的行為才會一致。使用 regex？

**Comment by uranusjr** [comment]
很遺憾，JavaScript 並沒有這麼高科技的功能。如果硬要做的話應該就只能用 regex 然後檢查合適的 codepoint range，不過 Unicode 裡的中文字其實很散，寫起來應該不會太好看，也不確定有沒有效能問題（應該是不會啦）。

或許直接考慮 byte count 會比較好？一般中文字在 UTF-8 encode 後是三個 bytes，這樣出來的結果應該⋯可能⋯也不會⋯差太多？

如果真的要 1:2 的話就只能用 AJAX 硬來了，直接開個 API 後端算完後再丟回去。反正也沒那麼多人投稿，server 應該擋得住（慢著）。

**Comment by ccwang002** [comment]
bytes 感覺不是一勞永逸的做法啊。這真的要做的話，日韓文（還有什麼語言會有寬符？）就一起考慮吧。

我傾向用程式從 Unicode data 撈出正確的 code point range 作成 regex。如果實作很複雜的話，就用 AJAX 撐吧。

剛剛還想到 grapheme 的處理，我想這做了就真的可以再投一篇了……（小聲）

**Comment by uranusjr** [comment]
寬字符[在 Unicode 裡有定義](http://www.unicode.org/reports/tr11/)。我不確定 Python 有沒有現成的工具，不過要做是一定能做的。

剛看到有人[在 JavaScript 實作這個](https://github.com/vangie/east-asian-width)了，不過不知道能不能用。我過幾天研究看看。
