### ISSUE TITLE
[Proposal Form] 加開 slide lang 選擇

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#124]
讓講者選擇自己投影片用的語言。

**Comment by uranusjr** [comment]
這部分應該在語言選項增加就好了吧？用英文的人不會寫中文投影片才對。所以就是三個選項：英文、中文口述配英文文本、中文口述與文本。

**Comment by flywindy** [comment]
@ccwang002 加 Slide 語言選擇的主要目的是什麼？

**Comment by ccwang002** [comment]
就 TP 寫的，我覺得標示中英 slide 也不錯，能給會眾更多資訊。

**Comment by flywindy** [comment]
同 #131 ，不會在這次上線。

**Comment by ccwang002** [comment]
增加一個台語的選項，我想講者都用台語了，應該不在意是不是用英文的 slide 吧？
