### ISSUE TITLE
Add an Explicit Icon for Email Contact

### ISSUE THREAD

**Issue by l34marr** [pycontw/pycontw2016#129]
This seems handy and helpful,  right?
The link goes to mailto:organizers@pycon.tw
Here is the draft illustration for both header and footer. You should get the idea despite of my poor drawing.
![email](https://cloud.githubusercontent.com/assets/56113/13347763/bdfa2770-dcaa-11e5-8159-a4e0cad9cb88.png)

**Comment by ccwang002** [comment]
Sorry 我不小心 push 上來了……

目前長得像這樣：

![screen shot 2016-03-02 at 11 28 37 pm](https://cloud.githubusercontent.com/assets/1544283/13465021/be6033c6-e0ce-11e5-814c-e682f8f0fc05.png)

footer:

![screen shot 2016-03-02 at 11 30 54 pm](https://cloud.githubusercontent.com/assets/1544283/13465037/d740798c-e0ce-11e5-9ac0-6d6fdde3b808.png)
