### ISSUE TITLE
Add website content

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#13]
其實內容就用 [2015] 和 [2014] 的來改就可以

[2015]: https://github.com/pycontw/APAC2015WebContent
[2014]: https://github.com/pycontw/APAC2014WebContent

應該需要人手幫忙？

**Comment by flywindy** [comment]
通常是各組分下去，還是 PR 組負責處理？

**Comment by ccwang002** [comment]
應該只有各組清楚自己要寫什麼，所以最後要分下去。但一開始沒有個雛型會不好分工，我或 PR 組找人可以把初版的內容放上來

**Comment by flywindy** [comment]
那不如就先放之前的版本，然後再讓各組去改？
2014 和 2015 哪一版比較完整？

**Comment by ccwang002** [comment]
看 2015 就夠了

**Comment by flywindy** [comment]
我請設計師照 2015 做幾個版型，然後再把 2015 年的內容放上去 Staging Server 讓大家看了以後做調整。

**Comment by ccwang002** [comment]
話說頁面應該放哪裡比較好？

我在 #12 是直接放在 `/src/templates/speaking/xxx` （對應到 <http://tw.pycon.org/2016/speaking/xxx>），但數量增加之後，可能會蠻亂的，還是多個子目錄像是放到 `/src/templates/content/`

**Comment by flywindy** [comment]
之前的頁面我想重新整理過，所以我想直接去 [2015](https://github.com/pycontw/APAC2015WebContent) copy 就好了吧？應該不用先放到 Templates。

**Comment by uranusjr** [comment]
話說乾脆把所有這種純 HTML 頁面集中起來算了？可以把它們放在 `src/templates/content`，然後直接按照架構整理（例如 `about/pycontw2016.html` 和 `events/overview.html` 之類），然後直接寫個 catch-all 的 view 把 URL 導到正確的 template，這樣加起來會更方便。

我晚點先開個 PR 到 @ccwang002 的 branch。

**Comment by flywindy** [comment]
可以，這部分我打算請 Django Girls 的 Emily 幫忙。當初 website sitemap 也是她整理的 :)

**Comment by uranusjr** [comment]
上面說的[做好了](https://github.com/ccwang002/pycontw2016/commit/7264a560a81d3f099f698370447c055890b70577)。之後應該只要稍微講一下 template 要怎麼 override `{% block content %}` 應該就可以讓各組自己送 PR 進來。

不過我現在覺得用 `blocktrans` 翻譯好像不太好，看亮亮現在寫的 template 就覺得很瑣碎，而且這樣一整段翻譯只要改一個字就要重翻。或許比較好的方式是…

    contents/
        en/
            about/
            speaking/
            ...
        zh-tw/
            about/
            speaking/
            ...

然後我可以根據網站能語系去挑，如果沒有就 fallback 到英文，再沒有就 404。這個不會很難。但缺點是可各語系之間的內容比較容易脫節？不知道負責寫這些東西的人有沒有想法。（這時候就要 cue @ccwang002！）

對了說到翻譯，好像也該開個 Trasifex 專案了，總是要有中文版吧。有人要負責這個嗎？

**Comment by ccwang002** [comment]
喔我也覺得 blocktrans 不是很好的辦法，直接用語系分資料夾比較好。

對啊開 Transifex 比較好

**Comment by uranusjr** [comment]
我等你把 speaking 系列頁面 merge 進來再改好了，不然也沒東西可測。

**Comment by ccwang002** [comment]
Merged 啦，先測多語言架構

**Comment by uranusjr** [comment]
:+1:
