### ISSUE TITLE
更多 favicon 尺寸

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#132]
目前只有 32×32，好像可以有更多。如果有原圖的話我可以直接產生，最好要有到 310×310，或至少也有 260×260 以上。

**Comment by flywindy** [comment]
大尺寸是用來做什麼

**Comment by uranusjr** [comment]
例如像這裡

![screen shot 2016-03-25 at 15 26 20](https://cloud.githubusercontent.com/assets/605277/14040066/61968e4c-f29e-11e5-80fa-f5716fcee6a7.png)
