### ISSUE TITLE
Add sprint info (Events/Sprint)

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#138]
- [x] 首頁的時間可以改成 Apr 16 和 Jun 11
- [ ] 增加 Events/Sprint 內容
- [ ] 加到 Events/Overview 裡面

**Comment by ccwang002** [comment]
@keitheis 能幫忙整理 Events/Sprint 的內容嗎？

**Comment by keitheis** [comment]
OK 收到。
