### ISSUE TITLE
Add additional speakers

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#15]
Migrated from #7.

Ref: https://github.com/pinax/symposion/blob/master/symposion/proposals/models.py#L128

**Comment by uranusjr** [comment]
功能大致上有了，但不知道 UI 該怎麼做。

有 mockup 嗎 @ccwang002

**Comment by ccwang002** [comment]
我畫一下。放在 proposal update 裡面會太複雜嗎？

**Comment by ccwang002** [comment]
試試用 Github 回信

**Comment by ccwang002** [comment]
![mockup](https://cloud.githubusercontent.com/assets/1544283/12032607/005f6a82-ae55-11e5-8746-58290a6ea91a.JPG)
也不用做太複雜，一次只能加一個講者（by email？），沒有註冊就 error，成功就再加一個。

form 我覺得跟 proposal update 分開但同一頁就好。

用 Github 回信的附件會被丟掉…

**Comment by uranusjr** [comment]
我之前想到和 proposal update 做在同一頁的問題是，使用者進去 update 頁然後按多名講者新增/刪除時並不需要 submit，和頁面上其他東西（包在 form 裡面）有點不一致。不過反正我先做出來再說。

**Comment by flywindy** [comment]
PyCon US 似乎沒有這一塊，是我們才會遇到多名講者的問題嗎？

**Comment by uranusjr** [comment]
我看他們的 repo 裡是有實作 model 和 form（上面的連結）。沒看 UI 上長怎樣，但應該也有吧？他們是用 M2M 做所以應該是要創了 proposal 之後才能加 additional speakers。

**Comment by uranusjr** [comment]
我看 PyCon US 好像是分在另一頁，這樣似乎 UX 會比較對。先照這個做做看。

https://github.com/PyCon/pycon/blob/develop/symposion/templates/proposals/proposal_speaker_manage.html
