### ISSUE TITLE
增加記錄組組員名單

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#152]
### 紀錄組

Daniel（組長）
Andrew
三子
Vivian
Vagabond
啓豪
百香
Deimos
Heidern

**Comment by PetiteDan** [comment]
麻煩增加一個伙伴 Raphael 感謝

**Comment by PetiteDan** [comment]
麻煩增加一位紀錄組伙伴 「何彥蓁」

也就是紀錄組名單為
Daniel（組長）
Andrew
三子
Vivian
Vagabond
啓豪
百香
Deimos
Heidern
何彥蓁

**Comment by uranusjr** [comment]
是說紀錄組的英文是什麼啊，Records？

**Comment by PetiteDan** [comment]
我習慣用
PHOTOGRAPHY 這個字 感謝

/daniel/

是說紀錄組的英文是什麼啊，Records？

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/pycontw/pycontw2016/issues/152#issuecomment-202101796>

**Comment by PetiteDan** [comment]
Hey,

I just signed the petition "要求鼎泰豐停止虐待蛋雞，盡速制定「非籠飼雞蛋」使用政策！" and wanted to see
if you could help by adding your name.

Our goal is to reach 35,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/SjVdwPwKgd

Thanks!
Daniel

**Comment by tai271828** [comment]
剛才那個 comment 是怎麼回事  冏rz。Danial email 被 hacked?

**Comment by uranusjr** [comment]
@tai271828 I think so (I got one from him in my personal email address as well)
