### ISSUE TITLE
reviewed number change while sorting

### ISSUE THREAD

**Issue by lucemia** [pycontw/pycontw2016#155]
最前面的 reviewed 顯示的數字, 在有根據 reviewed 排序 與沒有根據 reviewed 排序時數字不一樣

EX: 
1. 某題目:  大XXOO reviewed 顯示為 1
2. 按 reviewed 排序
3. 大XXOO reviewed 顯示變成 6 了..

**Comment by uranusjr** [comment]
我覺得這好像踩到 Django 的 bug 還是怎樣⋯⋯

反正是 `order_by('?')` 的問題（說不定是已知）。預設的排序（亂序）產生出來的 query 會有個 `GROUP BY proposal.id, RANDOM() ORDER BY RANDOM()`。其中 `proposal.id` 本來就應該要有，這沒什麼問題，但那個 `RANDOM()` 就不對了，這樣會變成類似 `DISTINCT` 的效果，count 就全部變成 1 或 0。其他的排序結果就是正常。

最簡單的解就是不要 random，不然就得有人花時間去研究有沒有 workaround 或 patch 可以打。

**Comment by uranusjr** [comment]
其實如果用 `raw` 直接幹出來是沒問題啦，這可以接受嗎 XD

看起來 Postgres 和 SQLite 的 query 是一樣的，所以都可以支援。

**Comment by uranusjr** [comment]
Related ticket to Django: https://code.djangoproject.com/ticket/26390

**Comment by flywindy** [comment]
這我和 @daikeren 昨天有發現，而且不只這個問題，其實會重複出現同樣的 Talk。直接用  import random 解呢？我不是很喜歡 raw 啦XD

**Comment by lucemia** [comment]
先算出來後, `import random`  不錯

**Comment by uranusjr** [comment]
嗯，反正沒很多篇 reviewer 也不多，先取出來再 random.shuffle 應該就行了。

Django 的 ticket 變成 accepted 了，看來完全是個 bug。

**Comment by flywindy** [comment]
幫 Django Debug 這個 Talk 應該也可以講一下了

**Comment by ccwang002** [comment]
投兩個 talk 果然是對的 xd
