### ISSUE TITLE
取消 proposal

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#16]
Migrated from #7.

應該要在 proposal 加一個 bool 欄位 `cancelled`。比較麻煩的是要在 UI 有個合理的方式來 cancel。或許就直接做個紅色 button，post 到一個獨立的 view 來 cancel？

在 dashboard 的 proposal 列表也要有個方式標示某個 proposal 已被取消。半透明之類的。被取消的 proposal 還是可以點進去，但唯一的功能是 re-submit，必須完成（`cancelled` 重設為 `False`）之後才能繼續修改。

**Comment by ccwang002** [comment]
直接刪掉 proposal 呢？

**Comment by uranusjr** [comment]
讓他們可以 re-activate 這樣還有機會可以撈到取消後又反悔的人！

**Comment by flywindy** [comment]
我覺得至少 Wording 或是 Flow 要改，cancel 可能會被誤以為是不想編輯，回到上一頁。
一般 cancel & save 都是這樣用的。

**Comment by flywindy** [comment]
我想了一下，`Delete` 是比較合理的，另外通常這種情況欄位名稱我都會用 is_active = True or False。

**Comment by flywindy** [comment]
然後我覺得狀態顯示 和 `Reactivate` 這個按鈕應該也要在 `Dashboard`。

**Comment by uranusjr** [comment]
我會盡量選擇初始狀態是 `False` 的 flag，這樣可以避免初始化錯誤。如果還需要其他理由，[PyCon US 的版本也是 `cancelled`](https://github.com/pinax/symposion/blob/master/symposion/proposals/models.py#L130)。

Re-active 放在 dashboard 好像確實比較好，我改一下。狀態顯示是指什麼？

**Comment by uranusjr** [comment]
另外如果按鈕文字用 **Withdraw**（中文版**撤回**）如何？

**Comment by ccwang002** [comment]
好啊

**Comment by flywindy** [comment]
好吧，model 不改也沒關係，Withdraw 和 Reactive 的切換可以都放在 dashboard 嗎？

**Comment by uranusjr** [comment]
當然～
