### ISSUE TITLE
Review Stage 2

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#165]
- [x] Stage 2 說明文字 @ccwang002 
- ~~將 stage 1 每個人的 review 結果，複製到 stage 2~~
- [x] Review 頁面加上分數與 comment （匿名）
- [x] ~~修改 filter_reviewable 加上 `accepted__isnull=False`~~ 改成在 view 裡 filter，才能做有 `accepted` 資料的 proposal table
- [x] 顯示投稿人資訊 `submitter` 、`supplementary`
- [x] 新增 tab 顯示已被接受/拒絕的投稿列表

**Comment by uranusjr** [comment]
yes

**Comment by flywindy** [comment]
將 stage 1 每個人的 review 結果，複製到 stage 2，這就交給 @uranusjr 了！
然後說明文字交給 @ccwang002 
其他跟 UI 有關，就交給我吧（握拳）

**Comment by flywindy** [comment]
@ccwang002，我確定一下，現在想想，你 Stage 1 的 Reviews 是不是只是當備份使用啊......
因為顯示在 Review 頁面上的 `Vote` 和 `Comment` 應該都是 Stage 2 的吧？
最後會給投稿人看得應該也是 Stage 2 的版本......

只是拿來備份的話，不是 dump data 就可以解決了嗎 XD

**Comment by uranusjr** [comment]
Stage 1 的 review 結果不是上面就會用到了嗎，顯示給大家看啊。

然後我不太確定這要怎麼顯示。就用一個 table 放在 proposal 顯示的下面，打分數欄位的上面嗎？

**Comment by flywindy** [comment]
我一開始也是想說那是 Stage 1，可是後來想到可以 update review（修改是改 Stage 2），難道修改以後不會顯示出來嗎？XD

**Comment by uranusjr** [comment]
我本來是以為是第一階段的東西就保留，然後如果看了別人的內容有其他想法就再評一個新的，然後兩個都可以被所有人看到。不太確定對不對。

**Comment by flywindy** [comment]
我也不知道，這樣的話顯示要分 Stage 1 & 2? 呼叫一下 @ccwang002

**Comment by uranusjr** [comment]
對了有個問題，可以看到 review 的人是誰嗎？

**Comment by uranusjr** [comment]
我剛剛跟他確認過了，應該還是要保留。反正我就先把資料做出來，UI 再交給你。

**Comment by flywindy** [comment]
之前說過是匿名，所以決定是 Stage 1 & Stage 2 都顯示囉？
如果兩個都顯示的話，可能 Stage 2 只顯示有修改過的。（不然會重複）

**Comment by uranusjr** [comment]
我是打算就不 copy，然後 stage 2 如果想改，就建一個新的 `Review` instance 給他。

**Comment by uranusjr** [comment]
我把提到的東西做了一下，看上面的 pull request。今天跟亮亮討論過之後有一些地方有稍微修正（應該說⋯⋯澄清？），然後有些地方實際做下去才發現不太對，我一併改在一開始的 checklist 了。

另外亮亮說想加一個列表顯示已經被接受或拒絕的投稿，因為這些不會顯示在 review list 裡面。

**Comment by ccwang002** [comment]
sorry... 剛剛開完會才有辦法看這串討論。我其實對實作沒什麼意見，今天跟 TP 討論的結果就是不覆蓋，stage 2 有更新的話就存一筆新的記錄。至於自己更新前舊的評論，我覺得沒必要顯示。

> 另外亮亮說想加一個列表顯示已經被接受或拒絕的投稿，因為這些不會顯示在 review list 裡面。

之前有跟 Michelle 討論過，雖然那時候覺得不用做，但我想了一下，覺得還是要做。我是從學習的角度出發，這次邀了很多 reviewer 都是初體驗，我想讓他們知道其他人評同個 talk 的角度跟評語，如果不公布已經接受或拒絕的 talk 的話，現在看起來少了二十幾個，從總投稿數或最後上的 talk 的總數比例都很高。

實作應該不會太複雜？多一個 tab 然後把 status 是 accept/reject 的列出來。

**Comment by uranusjr** [comment]
> 我是從學習的角度出發，這次邀了很多 reviewer 都是初體驗，我想讓他們知道其他人評同個 talk 的角度跟評語 […]。

所以這些顯示的 talk 還是要可以看 proposal 內容和 review 的 table，只是不能 review 的意思？實作上應該滿簡單的。

**Comment by ccwang002** [comment]
對啊因為結果決定了不會再讓他們改，只要顯示而且。

**Comment by uranusjr** [comment]
好像差不多做完了欸，我好厲害(啥)

有空幫我測測吧，因為種種原因我明天應該有時間再修一下，如果有必要的話。

**Comment by flywindy** [comment]
（按讚）我等等來測～

**Comment by ccwang002** [comment]
看完 PR 了，整理一下。到了 stage  2 會有 3 個 tab：

1. Unreviewed Talk Proposal
2. Reviewed Talk Proposals (not decided)
3. Talk Proposals with Decisions

第一個 tab 跟之前一樣；第二個 tab 要 filter 掉已經接受/拒絕的 proposal（還沒做）；第三個 tab 裡面的 review 唯讀，但目前並沒有顯示自己 review 的結果。

弄好了之後應該就沒問題。我趕緊來加上文字。

**Comment by uranusjr** [comment]
我想問一下，第二點把已經接受/拒絕的拿掉是有什麼特殊理由嗎？感覺好像沒什麼影響。

**Comment by ccwang002** [comment]
沒什麼影響，但因為不能那些 review，和可以改的放在一起有點怪。

**Comment by uranusjr** [comment]
好那我就拿掉了，不過其實目前的邏輯是 stage 1 的 review 在 stage 2 本來就不能改，雖然有顯示但沒有 update 鈕。

**Comment by uranusjr** [comment]
OK 我把這兩個東西加上去了。我把自己的 review 結果放進 table，顯示在別人的 review table 下面。

**Comment by ccwang002** [comment]
這 issue 應該能光榮身退了 T___T
