### ISSUE TITLE
帳號設定

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#17]
Migrated from #7.

* [x] 修改密碼
* [x] 連結 KKTIX（HOW?）← 交給 @flywindy
* [x] 連結 Facebook（不知道能用來做什麼）
* [x] 連結 Twitter（同上）
* [x] 連結 GitHub

**Comment by ccwang002** [comment]
KKTIX 要問能不能開 OAuth，不然就變成要定期 fetch KKTIX 報名資料用 email 比對。

FB / Twitter / GitHub 用在講者個人介紹，就…可以連到他自己的那頁

**Comment by daikeren** [comment]
感覺 link fb/twitter/github 這些如果沒串登入的話幫助不大，直接填連結就好了吧？如果只是為了連到講這自己的那頁特地串起來好像沒啥意義？

**Comment by ccwang002** [comment]
目的只是方便連結個人帳號，不用做用  FB / Twitter / GitHub 登入的功能，填連結就好了。

**Comment by flywindy** [comment]
KKTIX OAuth，@uranusjr  已經問過了 XD
[KKTIX 帳號連結](http://support.kktix.com/forums/229961-kktix-general-discussion/suggestions/9746940-kktix-%E5%B8%B3%E8%99%9F%E9%80%A3%E7%B5%90)

**Comment by flywindy** [comment]
然後就流程上，是 CfP -> KKTIX 報名，所以應該是在 KKTIX 報名的時候填 PyCon 的連結。
在 CfP 的時候就先填 KKTIX 帳號不合理，有些外國人之前可能根本沒有 KKTIX 帳號。

另外，Matching 的方法，我不想用 `email`，因為人通常有很多組 email，填錯組就會對不起來。
目前我是想讓他們連到 /accounts/kktix-token/ （需登入），獲得一組 uuid，在 KKTIX 表單填那一組。

實務上來講，如果連票種也可以分開就更好了，這樣可以設那個欄位為必填，像 RubyConf 有一個特別的票種 [CFP Submitter](http://rubytaiwan.kktix.cc/events/rubyconftw2015)，我覺得還不錯，也可以鼓勵大家投稿。

**Comment by uranusjr** [comment]
那個問題是好久以前了，我覺得他們應該根本沒在看，應該要找個內線來問比較有用。

KKTIX 用 email 真的不太好，因為他們的帳號並不是這樣綁的。用 token 似乎可行，不過應該還需要如果有人忘記填的解決方案，因為報名資訊送出好像就不能改了（不確定）？

**Comment by flywindy** [comment]
用 Token 的好處就是比較不會填錯，一般都是複製貼上吧（誰 Token 用打的？）
另外，如果可以把 CFP 票種分開，Token 為必填，就不會忘記填了。
最後，KKTIX Order 可以修改，在 [Order List](https://kktix.com/account/orders) 點 Order No. 以後是可以進入修改頁面的。

**Comment by uranusjr** [comment]
Never underestimate the stupidity of your users…

如果可以修改的話就還好，只怕有講者突然瞬間放空跑去選一般票。

然後還有個問題：今年還有要搞三人套票嗎？如果有的話還要處理講者和非講者一起買套票的狀況。這應該很常見，畢竟套票的原始用意就是要讓會眾病毒行銷，應該很多講者會去拉朋友。

**Comment by ccwang002** [comment]
這目前還沒討論，但往年成效不錯，2016 應該會有套票。

總之要找到某個 KKTIX 報名完，只要有票就能拿得到的 ID / token / … 連結，
之後要通知沒報名的講者就會比較方便。

（測一下 github email 回覆，希望排版不要炸）

**Comment by flywindy** [comment]
補充今天討論的結果：
- 票種確定會分開（多 CfP 票種，需要填 PyCon Website Token）
- 取消團報票種，只剩下早鳥票、非早鳥票、CfP 票（票價同早鳥票）

**Comment by flywindy** [comment]
確認一下，我們有要在講者資訊那邊放其他帳號嗎？（純粹為了網站 Speaker info 顯示？）
KKTIX 那一塊我打算另外開一個 issue。

**Comment by ccwang002** [comment]
單純顯示用

**Comment by flywindy** [comment]
要單純顯示用的話，那就還是要開這個欄位，看要不要做驗證。

**Comment by uranusjr** [comment]
如果要驗證的話要怎麼做啊，直接送個 request 看看有沒有那個頁面？

**Comment by ccwang002** [comment]
不用驗證吧……這頂多出現在講者介紹那頁，不如先做贊助商那頁比較實際。
