### ISSUE TITLE
多國語系

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#18]
1. 開 Transifex 專案
2. 繁體中文翻譯
3. 設定 hooks
4. 其他語言？

**Comment by uranusjr** [comment]
有人有 https://www.transifex.com/pycon-taiwan/ 的權限嗎？

**Comment by ccwang002** [comment]
Keith 應該有

**Comment by uranusjr** [comment]
試試看這樣能不能召喚出來

@keitheis

**Comment by ccwang002** [comment]
有空來試試翻譯吧 at Transifex: https://www.transifex.com/pycon-taiwan/pycon-tw-2016/

**Comment by uranusjr** [comment]
求加入

**Comment by ccwang002** [comment]
等等喔，改成 zh-hant 比較好

**Comment by ccwang002** [comment]
Done

**Comment by uranusjr** [comment]
話說其實 English 好像也可以開，可以弄 smart quotes 之類的東西。

**Comment by ccwang002** [comment]
英文對英文嗎？不確定能不能做…

**Comment by uranusjr** [comment]
或者 en (base language) → en-us？

**Comment by keitheis** [comment]
我好像把所有的 Github 通知 mark 為什麼了，應該是召喚不出來 @uranusjr。
