### ISSUE TITLE
Events/Talk 有時間的議程表

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#183]
改的機會不多，但因為講者可能會調整啊什麼的，議程表會變動，所以看要不要把議程表寫死。

另外我發現 talk 少一個欄位是決定時間長度的，可能要加一下。

**Comment by uranusjr** [comment]
如果不寫死的話我是傾向另外開一個 model

~~~python
class ConferenceEvent(models.Model):
    info = 用 GenericForeignKey 連到 TalkProposal 或者 workshop、午餐/休息時段等等
    start_time = TimeField
    duration = PositiveIntegerField 顯示分鐘數
~~~

然後你就自己去排，最後前端就根據你排的內容產生。`ConferenceEvent` 會直接在 model 或 form level 確認各 instance 之間不會衝突。

我還有考慮過一些更潮的例如用 jQuery UI 做 drag and drop，不過好像沒時間了，基本功能做完再說。

不太確定上面的想法能不能符合實際狀況。你現在有大概的概念議程會需要怎麼排嗎？例如午餐與休息時段一定每天都一樣嗎？報到時段呢？會不會有同個時段有些地方 45 有些地方 25 分鐘？之類的考量。如果都一樣的話就可以先寫死，只需要考慮會變的部分。重點還是你需要什麼，只要你想好了基本上都做得出來。

**Comment by ccwang002** [comment]
不過你這樣一說，不寫死困難度還蠻高的。雖然現在有個時間表，會是像填洞的方式把 talk id 塞進去。但之後可能有一些大變動（例如 xxx 活動的時間對調，加入 30 min 活動之類）

這樣……感覺寫死比較簡單 T__T。

**Comment by flywindy** [comment]
附上設計：
![artboard](https://cloud.githubusercontent.com/assets/902332/14312667/d1c095d4-fc1f-11e5-9db2-0b636a363f35.png)


@ccwang002 這次有要開交誼廳嗎？

**Comment by flywindy** [comment]
附上設計：
![artboard](https://cloud.githubusercontent.com/assets/902332/14312667/d1c095d4-fc1f-11e5-9db2-0b636a363f35.png)


@ccwang002 這次有要開交誼廳嗎？

**Comment by ccwang002** [comment]
喔喔！感謝！！需要交誼廳，就先多一欄 （不過可能很多時段是空的）

**Comment by uranusjr** [comment]
如果全部廳每個時段都一樣（看往年好像是如此）那不會很複雜，每個時段和 room 別編個號用 choices 就搞定了。如果要像[美國人](https://us.pycon.org/2016/schedule/talks/)那種開始結束和吃飯時間都錯開的就會比較難。如果沒有需要可以試試做成動態的。

**Comment by starwilly** [comment]
話說議程和講者是不是要特別設計一下 mobile 版本的啊，感覺在當天最常用到 (?)

**Comment by ccwang002** [comment]
@uranusjr  R0 R1 R2 應該是完全一樣的時段，會多安排一欄放像 R3（交誼廳）這種非常態的活動，這欄的時間會比較亂一點。那再看看怎麼實作比較簡單吧。

@starwilly 這頁的確需要設計 mobile 版，當天會很常用。做不好也很容易被反應……

**Comment by uranusjr** [comment]
所以 R3 有可能 time slot 和其他廳完全獨立嗎？例如別人是 10–11 11–12，然後 R3 是 10.25–11.45 之類的？

**Comment by ccwang002** [comment]
會有 R3 是 11 - 12:15 這樣，所以恩……會完全獨立

**Comment by flywindy** [comment]
@starwilly 有的，我已經跟設計師說過這一頁需要有 Mobile 版本。

**Comment by uranusjr** [comment]
剛在看前幾年的議程發現，需要加一個 icon 標示不錄影的議程。

**Comment by flywindy** [comment]
追加 R3 的設計：

![screen shot 2016-04-27 at 6 43 46 pm](https://cloud.githubusercontent.com/assets/902332/14850005/cecbb5f4-0ca8-11e6-9ed2-4517a8a960fe.png)

色碼：`#021C6A`

**Comment by flywindy** [comment]
@uranusjr 不錄影先顯示，我之後加 icon。

**Comment by uranusjr** [comment]
差不多又到了問進度的時間了，有 static HTML 了嗎⋯⋯

**Comment by uranusjr** [comment]
我在 schedule-2 branch 加了一個 `templates/events/schedule.html`，可以用它來當基礎做。放在 `schedule` block 裡面就可以了，我再把它整進動態產生的程式。

**Comment by flywindy** [comment]
不錄影的 icon：
![icon_videobanned 3x](https://cloud.githubusercontent.com/assets/902332/15625357/4cb0b704-24d6-11e6-8a0b-24927464868a.png)

**Comment by starwilly** [comment]
我放在 `schedule-time-table` 這個 branch

**Comment by uranusjr** [comment]
可以多加幾個範例嗎？不太懂像第一天下午 R2 和二天下午 job fair 的格式要怎麼弄出來。

**Comment by starwilly** [comment]
最後是要做成什麼樣子啊，因為我是照設計稿弄的說

-- 
Star Willy

**Comment by uranusjr** [comment]
應該會需要的格式：

* 從 R0 到 R3 一整條，例如 keynote
* 從 R0 到 R2 一條，R3 空白或有同樣長度的活動
* R0 1 2 3 各有自己的活動，時間一樣
* R0 到 R2 有活動（可能一樣也可能各自不一樣），然後 R3 有比較短的活動。這個的 time column 會需要有兩格，然後前半部分兩格高，R3 則是一格的高度。
* R0 到 R2 有活動（可能一樣也可能各自不一樣），然後 R3 有比較**長**的活動。這個應該最麻煩，就是我之前問過，最後用 `pull-right` 解的那個。

我等等用純 Bootstrap 做一個範例好了。

**Comment by uranusjr** [comment]
http://jsbin.com/sopuzaroqo/edit?html

大概需要這些。格線粗細的問題應該也要處理，但我懶得調了⋯⋯

最後兩個 case 的高度必須要做彈性一點，比較高的部份不一定會佔幾個時段。

**Comment by starwilly** [comment]
OK，現在在外面，回家再研究一下

**Comment by ccwang002** [comment]
想問一下要怎麼使用，我今天晚上可以幫點忙。

**Comment by uranusjr** [comment]
目前我實作的方法就是輸入一些 event model 實例來代表有哪些時段要填，然後你（或其他有權限的人）可以用 `/events/schedule/new/`（應該是，有點忘了）這個頁面觸發 `renderers.py` 裡面的函式 render 一個 HTML table 出來，然後按頁面上的 submit 按鈕儲存。這會把整個 render 出來的 HTML 資料存到 `Schedule` model 裡，之後一般人訪問 `/events/schedule/` 時，會直接用這個 model 裡面的 HTML，而不是重新 render。

現在 renderers 是用 Bootstrap 產出一個暫用的 HTML，還差 CSS，以及可能要稍微修改 HTML（class name 之類的）。這部分就是 @starwilly 現在正在做。

**Comment by ccwang002** [comment]
怪不得需要 talkproposal dump……能不能直接分享一個 db.sqlite？

**Comment by uranusjr** [comment]
其實我還沒匯入 XD 我應該會把它寫成一個 data migration，等等來做。

**Comment by starwilly** [comment]
話說你有做暫用的 html 在哪裡? 我可以拿來改....我週末照 design 刻的那個不能應付那麼複雜的格式...整個都做白工了 T . T

**Comment by uranusjr** [comment]
我 render 出來的 HTML 就和上面那個 fiddle 差不多，應該只差一些 class 名字而已

**Comment by uranusjr** [comment]
啊，不是 fiddle 是 JSBin

**Comment by starwilly** [comment]
我更新了一些，還有一些東西要微調。 先看一下結構 ok 嗎

**Comment by uranusjr** [comment]
看起來 OK！

對了上次和 @flywindy 討論的結果是時間要把開始和結束都寫出來。現在只有寫開始時間。

**Comment by ccwang002** [comment]
OK
![screen shot 2016-06-01 at 12 39 33 am](https://cloud.githubusercontent.com/assets/1544283/15682655/5b21d24c-2791-11e6-8490-94a84ba4c317.png)
