### ISSUE TITLE
Ticket Info

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#184]
設計：
![artboard](https://cloud.githubusercontent.com/assets/902332/14312976/810bfd48-fc21-11e5-8790-4ffca40402d9.png)

**Comment by ccwang002** [comment]
很有可能「Buy」對應到的連結都是一樣的 KKTIX 頁面，應該沒關係？

**Comment by flywindy** [comment]
我覺得沒關係，因為每個人應該只會想選自己想買的票種。
而且這個設計比較彈性，如果突然想分開連結也方便修改。

**Comment by flywindy** [comment]
Content 可以參考去年網站：https://tw.pycon.org/2015apac/en/registration/

**Comment by uranusjr** [comment]
價格要用 $ 還是 NTD（或者 NT$，這個好像是最常用的）要統一。和 #181 同理。

**Comment by lentychang** [comment]
1. 尚缺講者票的票價,我忘記是多少了 等我聯絡上sosory再改
2. 內文最後一項Tutorial 官網還沒有連結,到時有了之後還要新增

內文連結如下：
[中文](https://docs.google.com/document/d/1-tgpozpxVpKRCr-pVWVObq94-D6I4zYIoV7uKh8tOu8/edit?usp=sharing)
[英文](https://docs.google.com/document/d/1STlnD9DK1k5M_EklYGpWNeLvJuIDh9-c3eU-U8AEsC8/edit?usp=sharing)
