### ISSUE TITLE
Venue 相關頁面

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#185]
會場資訊 - 設計： 
![artboard](https://cloud.githubusercontent.com/assets/902332/14313068/12c8af38-fc22-11e5-995f-8aaa08c5b4fd.png)

住宿資訊 - 設計：
![artboard](https://cloud.githubusercontent.com/assets/902332/14313164/9af187ae-fc22-11e5-951d-5687d6292365.png)

**Comment by ccwang002** [comment]
<img width="953" alt="screen shot 2016-04-18 at 3 23 03 pm" src="https://cloud.githubusercontent.com/assets/1544283/14596506/7ea75d8e-0579-11e6-94b0-d09cf77a8c06.png">

目前長這樣。@flywindy 大請看，也看看設計師有沒有調整的
