### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#186]
設計：
![artboard](https://cloud.githubusercontent.com/assets/902332/14313433/2ceb97ac-fc24-11e5-8ceb-12d11dfacb6c.png)

**Comment by uranusjr** [comment]
這個看起來和其他 content pages 一模一樣，應該是有文案就可以上了。

**Comment by chairco** [comment]
@flywindy  Tutorial 內容如果需要幫忙補充請告訴我。

目前 KKTIX 課程已經放上去了
1. [ PyCon TW 2016 Tutorial - Creating python app with MySQL Router and MySQL Group Replication ](http://pycontw.kktix.cc/events/pycontw2016-tutorialsql) inline link.

2. [ PyCon TW 2016 Tutorial - Learn to become a full-stack developer with Raspberry Pi + Python + C ](http://pycontw.kktix.cc/events/pycontw2016-tutorialrpipythonc) inline link.

**Comment by uranusjr** [comment]
不知道要去哪裡回報

> The Tickets are only availabe for those who have already **baught** tickets for PyCon.

錯字

> The tutorial will be held if there are **more than 5 participants**. If the tutorial won't be held, PyCon will return full ticket price.

中文看起來是五人成班。More than 代表六人成班。另外 if 的文法不對，不過這個是小事。

> Please provide your Company Name and **Tax ID**.

是說 PyCon 網站和 KKTIX 加起來不知道有幾種統編的翻譯。

**Comment by chairco** [comment]
@uranusjr  先謝謝 TP，上線一陣子我沒有仔細檢查。已經回報給註冊組把錯誤部分修正。 那個統一編號翻譯目前看到兩種  Tax ID 和 Unified Business Number, 國外有統編這種說法嗎？我也不清楚，但也一併回報給註冊組建議用和 PyCon Taiwan 官方網站相同用詞會精準點。

**Comment by uranusjr** [comment]
就我所知英語圈沒有對應到統一編號的東西，之前好像也沒有很嚴謹的翻譯，我記得好像某年有看過用 VAT Number 的，不太記得。一般應該是不會有什麼問題啦，外國人不懂也會問，重點還是要統一。可能之後也可以做成 checkpoint 要求一下，看誰在檢討會的時候再提出吧。

**Comment by lentychang** [comment]
1. 先暫時改成 Unified Business Number
2. more than 5 people 改成 more than 4 people.
3. If 的文法錯誤請告知 或者明天我再看查查文法

**Comment by uranusjr** [comment]
一般會寫 *PyCon will return full ticket price if the tutorial* ***is not*** *held*，不過這邊和前一句的用詞太重複，也可以寫成 *PyCon will return full ticket price if the tutorial* ***is cancelled***。

**Comment by chairco** [comment]
反過來看應該會比較容易理解
If the tutorial is not held, PyCon will return full ticket price. 代表現在與未來表示一個真實 所以if 文法要用簡單句

**Comment by uranusjr** [comment]
其中一個已經結束了，另一個⋯⋯？

然後首頁還是 TBD。

**Comment by chairco** [comment]
目前確認是 MySQL 採免費報名參與，但須同時報名主議程
另一個經過討論，目前人數不足停開，但可能在議程後修改文案後重開
因為 MySQL 已經確認，不知道能否請 @flywindy 幫我們先把 MySQL 文案放上(和kktix同)，然後另一個 tutorial 先不要放上去，我最晚十點可以上來發 PR 如果到那時還請 TP 大大或其他有空捧友幫我 merge 一下

**Comment by flywindy** [comment]
我今天沒空更新，所以更新好了再請 @ccwang002 review，我負責 merge。

**Comment by ccwang002** [comment]
收到，先請 @chairco 更新

**Comment by chairco** [comment]
@ccwang002  #274 我新增 tutorial 中英文頁面，也更新總覽 Tutorial 說明（連結到 tutorial 頁面）請幫我 review ，然後幫我新增 活動（event） 下拉選單 。謝謝。

**Comment by uranusjr** [comment]
Closing since we’re freezing features for 2016.
