### ISSUE TITLE
Lightning Talk

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#188]
設計：
![artboard](https://cloud.githubusercontent.com/assets/902332/14314032/9f30e012-fc27-11e5-93f3-d301b9561091.png)

現場報名，所以 Content 不會先有。

**Comment by flywindy** [comment]
Questions：
- 目前 Lightning Talk 是排在 Day 3?
- 需要寫 Models 嗎？(寫 Models 可能到時候放會比較快)

**Comment by uranusjr** [comment]
為了不要會議當天還得 deploy 或許寫一下比較好

**Comment by uranusjr** [comment]
這個還有必要做嗎 @ccwang002？如果要做的話需要把 UI 刻出來。

**Comment by ccwang002** [comment]
這個不做啦！我先關掉囉
