### ISSUE TITLE
Staff UI 更新

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#189]
設計：
https://tw.pycon.org/2016/en-us/about/staff/

![artboard](https://cloud.githubusercontent.com/assets/902332/14314314/1f9a219a-fc29-11e5-82df-64ececf9ae40.png)

**Comment by uranusjr** [comment]
有稱號的一定要和別人放不同行嗎，這樣很難做，除非改 data structure⋯⋯

**Comment by flywindy** [comment]
這個不是從資料庫裡面撈吧？

**Comment by uranusjr** [comment]
現在是寫成一個 dict

**Comment by flywindy** [comment]
那沒有很難改吧 XD

**Comment by uranusjr** [comment]
你都這麼說了那就你改喔。

**Comment by ccwang002** [comment]
\ flexbox / \ flexbox /

Disclaimer: 我不會用

**Comment by uranusjr** [comment]
ping

**Comment by uranusjr** [comment]
Closing since we’re freezing features for 2016.
