### ISSUE TITLE
Reviews 記住切換的 tab

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#190]
現在有三個 tab 之下，用起來尤其明顯，上一頁的時候回不到本來打開個 tab。
目前覺得可以用 `#` 記起來。

**Comment by uranusjr** [comment]
+1

這個我之前有想做，後來就犯懶了。

**Comment by flywindy** [comment]
咦！你講這句話，我以為下一步是你自己 assign 自己。

**Comment by uranusjr** [comment]
Review 都結束了

![y0ujc](https://cloud.githubusercontent.com/assets/605277/14579674/a7c1eafe-03e4-11e6-9d34-ef788462372e.png)
