### ISSUE TITLE
KKTIX 講者報名 token

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#197]
http://pycontw.kktix.cc/events/pycontw2016-speaker
- [ ] [KKTIX 講者報名表單](http://pycontw.kktix.cc/events/pycontw2016-speaker)加上 token @flywindy
- [ ] `/accounts/token/` 可以直接取得講者 token @uranusjr 
- [ ] 需要判斷在資料庫 `proposal.accepted = True` 才取得 token 嗎？ @ccwang002

**Comment by ccwang002** [comment]
現在講者票是採邀請制的（今早才知道），所以應該不需要 token？

**Comment by flywindy** [comment]
好喔！
