### ISSUE TITLE
Menu 太長會爆掉

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#200]
<img width="892" alt="screen shot 2016-04-16 at 4 37 13 pm" src="https://cloud.githubusercontent.com/assets/1544283/14579989/82e73fb0-03f1-11e6-91d8-07c2b7b75386.png">

其他寬度都還好，就這個 case 比較討厭。可能要看直接用 collapsible 或 hide 某些東西來調整。之後 menu 會更長，所以要注意一下。

**Comment by ccwang002** [comment]
（這個是 TP 用我的帳號發的…補充一下 xd）

**Comment by uranusjr** [comment]
英文版在我的螢幕上正式爆炸了 🎉🎉🎉

![screen shot 2016-04-28 at 00 28 46](https://cloud.githubusercontent.com/assets/605277/14859795/5aa1bdb0-0cd8-11e6-90fe-4c51926d6b47.png)

**Comment by flywindy** [comment]
我有發現，明天跟設計師討論，目前想到左邊的 Logo 可以換，DASHBOARD 說不定可以換 logo，語言可以簡寫等等。

**Comment by uranusjr** [comment]
先關，2017 再根據 2017 的前端來改。
