### ISSUE TITLE
email 帳號

### ISSUE THREAD

**Issue by daikeren** [pycontw/pycontw2016#21]
我們在 email activation 的時候要用個官方帳號吧？現在有嗎？

**Comment by uranusjr** [comment]
去年好像是用 registration@pycon.tw 但我不知道要去哪裡拿。有了之後把 [`DEFAULT_FROM_MAIL`](https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-DEFAULT_FROM_EMAIL) 設起來就行了。

**Comment by daikeren** [comment]
啊... 剛剛發現我其實有帳號，有空我來搞定
