### ISSUE TITLE
KKTIX 註冊頁的飲食習慣

### ISSUE THREAD

**Issue by anniehuang921** [pycontw/pycontw2016#216]
飲食習慣的英文應該
Habbit-->Habit

請相關人員幫忙了～謝謝＾＾
![graph](
https://cloud.githubusercontent.com/assets/8927518/14628122/843ff88c-062d-11e6-82fe-4a06ea90c30d.png
)

**Comment by flywindy** [comment]
呃...KKTIX 好像不是網站組負責的，我幫你 pass 給註冊組。

**Comment by anniehuang921** [comment]
謝謝 @flywindy : )

**Comment by timtan** [comment]
我先快快看一下

**Comment by timtan** [comment]
這個資料看來只能讓註冊組想辦法了。

kktix 系統回  "活動須在未發佈狀況才可修改表單資訊。"

**Comment by uranusjr** [comment]
總之因為與網站無關，就先關閉。
