### ISSUE TITLE
CfP Markdown

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#22]
Markdown 編輯和 preview 目前是打算怎麼做？
有考慮用類似 [django-pagedown](https://github.com/timmyomahony/django-pagedown) 嗎？
還是 @uranusjr 想自己寫 XD

**Comment by ccwang002** [comment]
他做好了 XD 現在已經有了（用 SimpleMDE）

**Comment by flywindy** [comment]
我剛測試的時候沒試出來 XD
