### ISSUE TITLE
Abstract and Speaker Bio in multiple paragraphs

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#223]
As requested by a speaker,
> Could you show the abstract and bio in multiple paragraphs? Since I put the two language versions, currently, you put them in the single paragraph, and that makes my abstract and bio look strange.

**Comment by uranusjr** [comment]
Speaker bio 的修正我有加在 #222。Abstract 等等加上。

**Comment by uranusjr** [comment]
Tag 錯了，是 #219 才對
