### ISSUE TITLE
Sponsor talk 內容上線

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#224]
這邊收集了幾場 sponsor talk 的內容了，但不確定要怎麼做放到網站上。

我需要讓講者都先註冊帳號、開 proposal 嗎？不過照之前的說法應該是要加 sponsor talk label？

**Comment by uranusjr** [comment]
或許直接用一個 model 會比較方便。現在 sponsor 的活動都是演講嗎，還是會有 workshop？我想應該可以把我之前做的 schedule 相關功能先 merge 一些出來（本來打算這週再看一下，下週就可以完成）。

**Comment by ccwang002** [comment]
目前都是演講，workshop 可能有還再談，但最好一起做不然臨時冒出來蠻麻煩的。

schedule 現在是已經可以動了嗎？

**Comment by uranusjr** [comment]
還沒做 UI，但可以一起放在現在那個 list 裡面。

如果是都有可能的話那乾脆就用現在的 event model 好了。除了贊助商演講之外還有可能有什麼其他需要加 label 的東西嗎？

**Comment by ccwang002** [comment]
我有想到幾個 label。

一般的 talk：

- 語言（英文、非英文）
- Python 難易度
- 分類
- 能不能錄影

其他的暫時想不到 @@ 至少放個 url 可以連出去吧。例如像 on-site tutorial，有個連結就沒問題了。

**Comment by uranusjr** [comment]
我自己想到的也差不多，這樣看起來大部分的 tag 應該都已經在資料庫可以對應了。這樣就幫贊助商活動加一個欄位就好。

我大概明後天就先弄出來 event model 先把贊助商放上去吧。

**Comment by ccwang002** [comment]
感謝！！應該可以動了！
