### ISSUE TITLE
Custom error pages

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#23]
如果真的網站 404 至少也要好看一點

**Comment by flywindy** [comment]
404 和 500 都需要請設計師設計。

**Comment by flywindy** [comment]
目前只寫了一個很普通的 404 頁面，這星期請設計師再調整一下。

**Comment by flywindy** [comment]
404 page：
![artboard](https://cloud.githubusercontent.com/assets/902332/12666504/77cd041e-c67c-11e5-9d6e-0195b44a642d.png)
500 page：
![artboard](https://cloud.githubusercontent.com/assets/902332/12666506/7ddd61aa-c67c-11e5-8d14-bce66c82e783.png)
這兩頁我覺得沒什麼問題，會直接做。

**Comment by flywindy** [comment]
我想到問題了 XD
navbar 在前後台會不一樣，所以這邊我會略為調整。

**Comment by uranusjr** [comment]
直接把 status code 寫在上面有點怪，即使是參加 PyCon 的人也很少能直接看到 404 和 500 就反應現在是什麼狀況吧。

不過還是可以直接做，之後再調整用詞不難。

另外我覺得可以不用做 navbar，只要留右上角 icon 回首頁就好。這類頁面應該盡可能減少需要運算的東西，否則如果（舉例）navbar 的程式出問題 → 500 → 顯示 500 的頁面程式又 crash 這樣會很慘…

**Comment by flywindy** [comment]
Github 上面也直接寫啊，我覺得這還好吧。下面還有小字描述啊

新版本：
400：
![artboard](https://cloud.githubusercontent.com/assets/902332/12671557/6cc3b390-c6ab-11e5-80d5-ed3abf6dba5f.png)

500：
![artboard](https://cloud.githubusercontent.com/assets/902332/12671544/55addce4-c6ab-11e5-8069-6315a2711e1b.png)

**Comment by uranusjr** [comment]
好吧那就這樣，不過裡面英文有點不通可能要修一下。然後新版 icon 上面可能要加一行說明點這個可以回首頁。

然後我突然想到，這頁應該也要有中文版？

**Comment by flywindy** [comment]
字我會微調，呃.....有 404 page 還要做多語言的範例嗎？我疑似沒用過這種網站.....

**Comment by uranusjr** [comment]
很多吧，例如 Facebook

**Comment by flywindy** [comment]
Facebook... 你一定要舉這麼特殊的例子嗎？那就做吧！交給你了

**Comment by uranusjr** [comment]
不太確定你判斷例子的標準是什麼…

**Comment by flywindy** [comment]
例如 PyCon JP 也有做，我寄設計檔給你了。
