### ISSUE TITLE
Catch-all flatpage views show 500 on staging

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#24]
See http://pycontw.krdai.info/2016/speaking/cfp/

我試過用 `settings/production.py`（只改 `ALLOWED_HOSTS` 其他設定都相同），但沒辦法在本地重現。誰能看 server 上面的 log 幫一下拜託～

cc @daikeren

**Comment by daikeren** [comment]
My bad. 上面的 virtualenv 忘了換成 python3 orz
