### ISSUE TITLE
如果 visitor 是投稿人本人，在 proposal page 直接修改連結

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#242]
還要去 dashboard 找好麻煩。

**Comment by flywindy** [comment]
我覺得這個還好吧，去 Dashboard 修改比較一致。

**Comment by flywindy** [comment]
還是你是說提供快捷連結？

**Comment by uranusjr** [comment]
對，就是在 proposal page 加一個連結連到修改的頁面。不然現在的流程是看到 proposal 後 → 按 dashboard → 找到 proposal → 按修改，上次做了一遍覺得很麻煩。加個連結也很容易，沒什麼損失。

**Comment by flywindy** [comment]
UI 有點怪，加上這功能有點像彩蛋。最後沒有上先關掉吧～
（留給明年）
