### ISSUE TITLE
增加 PyDay 售票訊息

### ISSUE THREAD

**Issue by chairco** [pycontw/pycontw2016#256]
增加票價說明、KKTIX 票價連結。 #255

**Comment by flywindy** [comment]
@chairco 麻煩檢查一下內容有沒有問題：
https://pycontw.krdai.info/2016/en-us/events/pyday/
https://pycontw.krdai.info/2016/zh-hant/events/pyday/

要等 KKTIX 的連結加上去後再上線嗎？

**Comment by chairco** [comment]
@flywindy 謝謝您，內容沒有問題。
