### ISSUE TITLE
共筆區與聊天室的連結

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#263]
共筆：http://hackfoldr.org/pycontw2016/
聊天室：https://gitter.im/pycontw/2016

先筆記一下，之後要找個地方放這兩個連結。

**Comment by chairco** [comment]
我發現，共筆被清掉了 ＠＠ 。

**Comment by uranusjr** [comment]
我看連結裡東西都還在啊？

**Comment by chairco** [comment]
咦，出現了，我猜可能是網路問題，不好意思。
