### ISSUE TITLE
Talk schedule cells have overlapped text

### ISSUE THREAD

**Issue by yungyuc** [pycontw/pycontw2016#272]
See the "2B or not 2B ..." as an example.  In both Chinese and English locales the texts are too long and overlaps with the speaker's name.

![screen shot 2016-06-02 at 10 28 07 pm](https://cloud.githubusercontent.com/assets/399122/15748394/4facb3ba-2911-11e6-9df2-7e746b58ef55.png)

**Comment by uranusjr** [comment]
Thanks for the report. We are aware of this issue before publishing, but though we should push out something first. The patch is already being reviewed; hopefully we can fix this tonight.
