### ISSUE TITLE
debug_toolbar: sqlparse 0.2.0 api changed

### ISSUE THREAD

**Issue by note35** [pycontw/pycontw2016#280]
**Reproduce**
http://127.0.0.1:8000/en-us/accounts/login/?next=/en-us/dashboard/
Enter any username and password -> Login

**Error message**
builtins.TypeError
TypeError: process() missing 1 required positional argument: 'stream'

**Solution**
https://github.com/jazzband/django-debug-toolbar/pull/854/files

Regards

**Comment by uranusjr** [comment]
So is the real solution upgrading Django-Debug-Toolbar? What version would it work?

**Comment by StanleyDing** [comment]
Upgrading to 1.5 solves the problem. Upgrading to 1.6, however, needs some tweaking.
