### ISSUE TITLE
PyCon Talk Proposal

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#30]
收集一些開發時遇到的題材，到時候投稿的時候可以參考。有其他覺得值得放的也歡迎提出～

**TODO: 決定誰要上去講。**

* Email as username
    * Model and manager
    * Login form field (#28)
* Database-less 註冊認證  (#3)
* pytest 與 pytest-django
* UI testing with lxml
* Markdown in proposal (457e4ee and #20)
* Proposal withdraw (#16)
    * 直接刪掉？
    * Wording
    * 按鈕放哪裡
* Catch-all template views (7264a56) + 多語系支援 (#19)
* Transifex 整合 (#29)
* `.mo` 檔是否該放入 `.gitignore` (https://github.com/pycontw/pycontw2016/pull/29#issuecomment-167151312)
* Travis CI 整合
* 把 Fabric task 當成 helper script
* URL-based 語系選擇 (#31)
    * `en-us` in Django
    * Smart quotes/dashes (別名：英文需要翻譯嗎？)
* Additional speakers
    * UI 怎麼做
    * Cancelling
    * Playing with generic relations
    * Optimise database queries with relations (and generic ones!)
* Testing by mocking behavior (#108)
    * monkeypatch by pytest
    * unittest.mock

**Comment by timtan** [comment]
全講

---Sent from Boxer | http://getboxer.com

On 2015年12月25日 GMT+8 上午3:32:18, Tzu-ping Chung <notifications@github.com> wrote:收集一些開發時遇到的題材，到時候投稿的時候可以參考。有其他覺得值得放的也歡迎提出～  TODO: 決定誰要上去講。   Email as username  Model and manager  Login form field (#28)      Database-less 註冊認證   pytest 與 pytest-django  UI testing with lxml  Markdown in proposal (457e4ee  and #20)  Catch-all template views (7264a56 ) + 多語系支援 (#19)  Transifex 整合 (#29)   .mo  檔是否該放入 .gitignore  (#29 (comment))  Travis CI 整合  把 Fabric task 當成 helper script    —Reply to this email directly or view it on GitHub.

**Comment by ccwang002** [comment]
這可以拆成兩個 talk 了 xd

一個中級講一些像 widget / testing / ci / email auth
一個進階講多國語言、catch all template、UI testing
