### ISSUE TITLE
Keynote 和贊助頁面設計

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#300]
去年的：

https://tw.pycon.org/2016/en-us/events/keynotes/
https://tw.pycon.org/2016/en-us/sponsors/

大概就是框框和圖片要決定一下吧，然後看標題要用哪一種。

**Comment by chairco** [comment]
目前 Keynote 有幾個想法，希望設計者給予指教
1. 目前版面好像跑掉，可以看到 footer (底頁) 跳到頁面中間
2. 2016 Keynote 的 Bio 和 演講大綱 是放在照片右邊，照片下面是放講者的社交、個人網頁等連結，覺得不錯可以延續。
3. 因為今年網站整體顏色是暗色系，白色底感覺好強烈啊

想知道今年風格，謝謝囉。

目前頁面效果（比較大會比較慢）：
![screencapture-events-keynotes](https://cloud.githubusercontent.com/assets/7709136/22232183/e54d3442-e222-11e6-82eb-3e97533dc76b.png)

**Comment by starwilly** [comment]
先打一下目前的想法：
- 應該會把 keynote speaker 放到首頁，有 avatar 和個人連結，然後詳細資訊應該會做成 modal / slideshow
- Block 會換成深色的底色
