### ISSUE TITLE
travel-info 的介紹文擴充跟介面設計

### ISSUE THREAD

**Issue by note35** [pycontw/pycontw2016#304]
> This page is written in English ONLY currently

1. 這頁之前還沒有被完成，可能需要請有志者一起擴充更多的內容。
2. 內容豐富之外，可能會需要相應的前端介面。

其他請補充。

**Comment by ccwang002** [comment]
這頁只有英文原因，當初在撰寫的時候覺得中文圈的人大概不太需要這樣的簡介，所以沒有寫。這頁是從 [2014](https://tw.pycon.org/2014apac/en/venue/travel-info/) 改來的。

**Comment by uranusjr** [comment]
我看去年的頁面就只是單純的文字（加一張圖），「相應的前端介面」是只希望這頁可以有特殊的版面設計嗎？

**Comment by note35** [comment]
我目前唯一的點子大概是youtube影片的擺放跟呈現可能能多加設計一下，但或許不用所以我才說『可能』。

**Comment by uranusjr** [comment]
了解，會和設計再討論
