### ISSUE TITLE
Set lang by URL 

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#31]
Continue work from #29 and #18.

Ex:

- /zh/ --> Use zh-hant
- /en/ --> Use en

**Comment by uranusjr** [comment]
用網址超麻煩der，可以直接用 session/cookie/使用者偏好設定/語系偵測 判斷就好了嗎～

**Comment by ccwang002** [comment]
但…以前是這麼做……

**Comment by daikeren** [comment]
用網址的好處是分享的時候可以確定內容的語系...

**Comment by uranusjr** [comment]
好吧… 乖乖做

**Comment by keitheis** [comment]
乖乖。:meat_on_bone:

**Comment by uranusjr** [comment]
樓上去去旁邊堆雪人 :snowman:

**Comment by keitheis** [comment]
:snowflake: :snowflake: 　:snowflake: 
:snowflake: :snowman: :snowboarder: :snowflake: 
　:snowflake:  :snowflake:
