### ISSUE TITLE
Contents 內 speaking 的內容

### ISSUE THREAD

**Issue by hsiaoyi0504** [pycontw/pycontw2016#312]
- talk
需要再把英文的example放進去
- cfp
Tutorial部分還沒有新的說明

**Comment by chairco** [comment]
#332 @jackklpan  協助調整了版面

* talk 部分的範例目前全部移到後台投稿的 form 下個別 field 下用 modal 做處理 #330 
* cfp 如何投稿教學在 `/speaking/tutorial/`， #331 有提到和 talk 內容不太一致 應該是指 `/speaking/cfp/`  和這兩頁稍微不同 `/events/tutorials/`。發現有些內容重複在個頁面，我要稍微做一下整合與整理。

**Comment by chairco** [comment]
#343 這邊做了更新。
