### ISSUE TITLE
在 talk proposal submit form 新增如何投稿頁面的連結

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#313]
在標題下面加一個 [Alert](http://getbootstrap.com/components/#alerts)，裡面告訴投稿人有這個文章可以看，附上連結（另開視窗）。

**Comment by chairco** [comment]
連結導到 `zh-hant/speaking/talk/` 這個位置

**Comment by chairco** [comment]
目前是第一次新增才會有 alert，新增之後填寫更多欄位之後是否還要？

**Comment by uranusjr** [comment]
我反而覺得填寫更多欄位時比較需要，因為新增 proposal 是幾乎所有欄位都是選擇題，新增完要填其他欄位時還更應該看如何投稿的教學。

**Comment by chairco** [comment]
在 `9b01d44` 補上。

**Comment by uranusjr** [comment]
This is done.
