### ISSUE TITLE
在 dashboard 的 proposal list 顯示未填的欄位

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#314]
如果有欄位空白，在 list 裡顯示未填的欄位列表。需要顯示的欄位：

* 摘要
* 演講目標
* 詳細說明
* 大綱
* 補充資訊
* 投影片連結

在 list view 的標題下面顯示一個[進度條](http://getbootstrap.com/components/#progress) 顯示填寫百分比，加上百分比文字與顏色分辨進度。

**Comment by chairco** [comment]
3q Nick

**Comment by uranusjr** [comment]
我稍微整理了一下程式 + 小修了一點 CSS 在 5bffa69，有興趣可以看一下。

**Comment by nick0916** [comment]
喔喔有看到了，這樣寫的確比較好ＸＤ，感謝整理
