### ISSUE TITLE
dashboard tablelist change password 在英文版，如果頁面太小會切版

### ISSUE THREAD

**Issue by chairco** [pycontw/pycontw2016#315]
如標題

**Comment by forwyl** [comment]
似乎沒有發現切版情況。以下附上在Firefox用360 x 640看的擷圖結果：
![1](https://cloud.githubusercontent.com/assets/6460751/23103231/d571cdf0-f6f2-11e6-9cb2-f96d708d2679.png)
![2](https://cloud.githubusercontent.com/assets/6460751/23103230/d5715c62-f6f2-11e6-8950-817811633db0.png)

**Comment by uranusjr** [comment]
不能過 md 的 breakpoint，例如 1024 寬左右。
