### ISSUE TITLE
特定投稿欄位加上按鈕，可以叫一個 popup 出來顯示範例（好/不好）

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#316]
在說明文字放一個連結，按下後用 [modal](http://getbootstrap.com/javascript/#modals) 跳出。裡面的範例文字做成可以直接讓議程組 contribute。

**Comment by chairco** [comment]
pop 像是 [COSCUP](https://coscup.org/2016/schedules.html)

**Comment by uranusjr** [comment]
Done in #323.
