### ISSUE TITLE
取代原本介紹 Markdown 的連結

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#318]
寫一個 cheatsheet，在連結另開視窗。

Cheatsheet 裡面放常用的語法，類似 [CommonMark 的教學](http://commonmark.org/help/)。要有中英文。

**Comment by chairco** [comment]
大概會用到幾個語法
```markdown
大標題: #h1 ##h2
項目: +, *, 1
文字效果:  ***
```

**Comment by note35** [comment]
**這個issue需要等到設計那邊將css有針對markdown_cheatsheet的顯示作處理後才能關閉**
