### ISSUE TITLE
Model change without migration on staging server?

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#32]
https://travis-ci.org/pycontw/pycontw2016#L697

**Comment by daikeren** [comment]
因為在 https://github.com/pycontw/pycontw2016/blob/master/src/proposals/models.py#L86 這邊有 reverse_lazy 的關係，production 環境會把 help_text 換掉，django migration 會偵測到這部分有動到。

**Comment by daikeren** [comment]
這邊我覺得沒啥大問題，就先 closed 了。
