### ISSUE TITLE
Slack 機器人

### ISSUE THREAD

**Issue by daikeren** [pycontw/pycontw2016#33]
有空會想來做做看，可以代替之前的投稿戰報，目前想到的有：

1. 在有人投稿的時候叫一下：XX 投了一篇叫做 OO 的題目
2. 每天定期發投稿戰報
3. 在連續 5 天都沒人投稿的時候，notify @ccwang002 說：已經連續 5 天都沒人投稿了，議程組要加油啊！

可以想想還有啥其他能拿來亂搞的東西 ...

**Comment by flywindy** [comment]
我覺得一開始 3. 可能很常出現 XDDDDD

**Comment by ccwang002** [comment]
5 天沒投稿就發一張基本崩潰照，10 天沒投稿就超級崩潰圖然後照三餐發簡訊給大家 T__T

1. 我覺得很不錯，但不能透漏投稿者啦。目前想到折衷的方法是用 類別、Python 難易度、目標聽眾。

**Comment by ccwang002** [comment]
@uranusjr 一般像這種 slack bot 是怎麼做，用 django signals 嗎？

**Comment by uranusjr** [comment]
老實說我沒做過… 應該是用 cron 比較快？直接寫個 management command 取出最新一篇的投稿是否在多久以內：

~~~python
python manage.py signal_latest_proposal --days=5
~~~

後面的參數可以用 `datetime.timedelta` 來 parse，然後取 `TalkProposal.objects.filter(created_at__gt=(now - delta)).exists()` 如果是 True 代表最近五篇有投稿，如果 False 就崩潰一下，然後寫個 cron job 每看多久執行一次之類的。

沒很認真想，而且其實我也沒做過 Slack bot…
