### ISSUE TITLE
英文文本需要潤飾

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#331]
看了一兩頁，有些英文⋯⋯不太像英文，可能要找人修一下。

**Comment by chairco** [comment]
嗯嗯，當初 event 下的幾個頁面請一些人幫忙看過，但看起來品質還是不夠。
TP 看到是那幾頁？我覺得不是很好的頁面像是總覽 (Overview), 教學 (Tutorial)。

**Comment by chairco** [comment]
keynote 那頁目前先簡單介紹，要再與講者確認介紹內容。

**Comment by uranusjr** [comment]
同意 overview 不太好，我沒仔細看 tutorial 但好像內容和 talk 那邊不太一致？
