### ISSUE TITLE
Proposal example modal 需要英文內容

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#333]
應該要把現在在 HTML 裡的內容換成英文，加上 translation tags，然後再從 Transifex 那邊補回中文翻譯。

**Comment by chairco** [comment]
Hi @uranusjr  #330 這篇重新把一些內容翻譯也加上 translation tags，不過因為當初這個範例是設定語言是中文，目前就暫時不做翻譯。

**Comment by uranusjr** [comment]
好那就先照新的版本，翻譯就之後再麻煩補上。

**Comment by chairco** [comment]
翻譯部分補上囉
