### ISSUE TITLE
Blockquote 的英文字型與其他內文不一致

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#335]
可以看 /about/pycontw/ 這頁。這是 intentional 嗎？

![screen shot 2017-02-06 at 16 00 14](https://cloud.githubusercontent.com/assets/605277/22638782/5efc52ac-ec85-11e6-874b-e306cee2bb30.png)

**Comment by linmic** [comment]
@uranusjr I've tweaked the HTML in this page for both `en-us` and `zh-tw` to make them look right. Please do remember to enclose `<p>` and other non-heading text elements with `<article>` to make the appearance consistent.
