### ISSUE TITLE
修正 content 頁面排版

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#342]
一些排版似乎還有點問題。我先把 `about/pycontw` 和 `about/code-of-conduct` 改了，麻煩檢查一下其他頁面也都正確。

主要需要確認

1. `<p>` 和其他內文有放在 `<article>` 裡面
2. 合適的 `<h1>` 和 `<h2>` 有用 `<span>` 包一層（這樣才會有漸層）

這個做完差不多就可以公開了！

**Comment by chairco** [comment]
好，我今天努力把它全部檢查完！

**Comment by chairco** [comment]
@uranusjr 第一點 延續問題，<h3></h3> 有建議風格是 <article></article> 外或是內嗎？如果都可以那我就不統一了。

**Comment by uranusjr** [comment]
看你想怎麼顯示，`<article>` 會產生一個黑色的方塊，如果你覺得某個子標題是內容的一部份，那就在裡面；如果你覺得這個子標題會把內容分段，那就分開。

**Comment by chairco** [comment]
大概有列在 nav 上的頁面檢查過，也做些修正。唯一可能比較有疑問是住宿頁面，看起來 <table> 沒有對齊。

<img width="1008" alt="2017-02-08 7 22 20" src="https://cloud.githubusercontent.com/assets/7709136/22735319/189ea32c-ee34-11e6-99b8-eeb0361ca6ed.png">

另外是還沒有上線的頁面 keynote。因為也還沒有與 keynote 確認 bio 也許晚些在上？ 翻譯部分在 tx 上都翻譯了 @uranusjr 意見呢？

**Comment by uranusjr** [comment]
> 另外是還沒有上線的頁面 keynote。因為也還沒有與 keynote 確認 bio 也許晚些在上？

我是這樣打算沒錯

> 翻譯部分在 tx 上都翻譯了

稍後更新!

**Comment by chairco** [comment]
謝謝 TP 💯 

剛剛試用隨便問一下可能是目前網址指向的問題，大頭照目前是 404。
<img width="1189" alt="2017-02-08 7 47 25" src="https://cloud.githubusercontent.com/assets/7709136/22736082/89ccf3ca-ee37-11e6-853f-2679bb86bc7b.png">

**Comment by uranusjr** [comment]
Profile picture 已修正

**Comment by chairco** [comment]
Hello @uranusjr  發現有一個摘要漏掉[連結](https://www.transifex.com/pycon-taiwan/pycon-tw/translate/#zh-Hant/djangopo/108013251?q=How%20the%20talk%20will%20be%20arranged.%20It%20is%20highly%20recommended%20to%20attach%20the%20estimated%20time%20length%20for%20each%20sections%20in%20the%20talk.%20Talks%20in%20favor%20of%2045min%20should%20have%20a%20fallback%20plan%20about%20how%20to%20shrink%20the%20content%20into%20a%2030min%20one)

<img width="775" alt="2017-02-09 3 05 34" src="https://cloud.githubusercontent.com/assets/7709136/22772773/8c273da4-eed9-11e6-94ab-d5cc2f2d654c.png">

🙏
