### ISSUE TITLE
venue.html 的 scss

### ISSUE THREAD

**Issue by chairco** [pycontw/pycontw2016#344]
2016 的 venue.html 頁面會使用 `css/pages/_venue.scss` 讓頁面有以下效果：

<img width="948" alt="2017-02-08 5 19 15" src="https://cloud.githubusercontent.com/assets/7709136/22730668/ded2d354-ee22-11e6-990c-bfcc1a44ae0b.png">

目前 2017 venue.html 因為沒有.scss 所以文字和一些控制項目會跑出圖片，變成這樣：

![screencapture-localhost-8000-en-us-venue-1486545584055](https://cloud.githubusercontent.com/assets/7709136/22730679/eaaa3de8-ee22-11e6-8a96-6517e4226b8f.png)

**Comment by uranusjr** [comment]
這之前是誰做的啊，亮亮嗎？

**Comment by chairco** [comment]
對的

**Comment by uranusjr** [comment]
來釣釣看 @ccwang002

**Comment by chairco** [comment]
應該是把 ` css/pages/_venue.scss` 加進去就可以，不過現在 content 頁面好像和 2016 方式有點不同不知道該怎麼處理 XDDD

**Comment by linmic** [comment]
我先看看

**Comment by linmic** [comment]
Fixed.

**Comment by chairco** [comment]
@linmic 👍

**Comment by ccwang002** [comment]
如果是深底色，可以選另一個深色的圖資，感覺比較搭。看來解掉了，有需要再釣(?)我吧。
