### ISSUE TITLE
關於頁面 (about.html) 的補充

### ISSUE THREAD

**Issue by chairco** [pycontw/pycontw2016#346]
有誰知道去年這個頁面的文案是誰寫的嗎？2017 我想引用 @uranusjr [專訪](https://pycontw.blogspot.tw/2016/11/python_29.html) 關於主席一些想法，但 2016 我覺得可能要請 @l34marr 來撰文或許比較適當？

![screencapture-localhost-8000-zh-hant-about-pycontw-1486560253915](https://cloud.githubusercontent.com/assets/7709136/22739095/19d7f9c6-ee45-11e6-9e15-365c58cd0a4d.png)

**Comment by ccwang002** [comment]
我沒記錯的話應該是 yyc

**Comment by chairco** [comment]
@ccwang002  謝謝啦！

**Comment by ccwang002** [comment]
非常抱歉，我找到原始的版本了，是 CCC 寫的

**Comment by ccwang002** [comment]
@chairco 我記錯了

**Comment by chairco** [comment]
@ccwang002 謝謝還幫我搜尋群組， 在問他之前剛剛是想把 2016 與 2017 分不同人寫，2016 應該是介紹回歸 PyConTW 深根的成果所以亮亮執筆覺得很合適比較能寫出感覺（不過知道您最近比較忙）？2017 是想介紹 TP 的理念這樣？

**Comment by ccwang002** [comment]
恩……最近有點忙，我可以幫忙補充，不過可能需要有人把大部份的內容生出來。如果是去年主席呢？

**Comment by chairco** [comment]
@ccwang002 ok 那我先去和 marr 提一下需求，我覺得他會很願意，然後再請 @ccwang002 幫忙看一下這樣

**Comment by uranusjr** [comment]
其實我有問公關組有沒有人想寫了 XD 早上再來抓相關人士 sync 一下

**Comment by l34marr** [comment]
I will add content for 2016 based on http://pycontw.blogspot.tw/2016/05/welcome-to-pycon-taiwan-2016.html

**Comment by chairco** [comment]
@l34marr @uranusjr Thanks~

**Comment by l34marr** [comment]
See #348 for my first draft about 2016. I know Zong-han Xie (from PR team) did another hard word on his version, hopefully we will come out a version all happy.

**Comment by uranusjr** [comment]
This is done, right?
