### ISSUE TITLE
Tutorial 翻譯沒有一致性

### ISSUE THREAD

**Issue by chairco** [pycontw/pycontw2016#351]
在 overview 頁面看到 `專業課程`
在 cfp 頁面看到 `課程`
主頁面則是翻譯為 `教學`

可能要一致性，不然太怪了。看大家比較喜歡哪個翻譯？

**Comment by uranusjr** [comment]
我只確定去年有定調用 tutorial 這個詞，但不確定中文翻譯是什麼。釣釣看 @ccwang002。

**Comment by ccwang002** [comment]
去年應該是不翻，因為沒有固定好懂的詞。中國是翻「教程」，全名可以是「教學課程」。今年就看大家的想法。

**Comment by uranusjr** [comment]
這麼快就釣出亮神 <(_ _)>

不然就翻譯成**專業課程**，簡稱**課程**好了。然後 workshop（如果有）就翻譯成工作坊。

**Comment by chairco** [comment]
😍 亮亮！好那就全部翻譯成 專業課程（課程）。

**Comment by chairco** [comment]
#354 已經解決掉，把這個關閉囉。
