### ISSUE TITLE
sprint 頁面新增 3/12 活動

### ISSUE THREAD

**Issue by chairco** [pycontw/pycontw2016#357]
請 @hsiaoyi0504  幫忙更新，可參考 [2016 頁面](https://tw.pycon.org/2016/zh-hant/events/sprints/)。

日期＆時間：
3/12 10:00 AM ~ 17:00 PM

內容：
審稿系統優化計畫開跑！

活動場地：
大安 CLBC

**Comment by uranusjr** [comment]
所以 3/12 就會開個網站的 sprint 的意思？

**Comment by chairco** [comment]
應該是在活動之前更新這個頁面，公告 3/12 會有第一個 Sprint 活動

**Comment by chairco** [comment]
補充活動詳細[內容](https://docs.google.com/document/d/1GAKnoAiydN8FPlGONxnUPZQAODYewx8KdUV_QK-kWSk/edit)

**Comment by uranusjr** [comment]
fixed in #359.
