### ISSUE TITLE
投稿分類增加 FinTech

### ISSUE THREAD

**Issue by chairco** [pycontw/pycontw2016#360]
稍微解釋一下，因為從去年贊助組一直很積極幫我們拓展 FinTech 相關贊助夥伴，然後去年我們也有幾場 FinTech 的贊助演講。

前天(3/1) Stanley 有提到希望 PyConTW 能找些夥伴來投稿 FinTech，所以我也和智程做了請求希望他能幫忙我們推廣，很高興今天收到他回訊答應我們。不過我發現投稿分類選項沒有 FinTech 這個選項，應該說今年其實也沒認真去請教大家這個分類是怎麼建立，今年我們主題是 AI 和 Data 其實還有一個分類是**資料分析**，不過如果要推 FinTech 大概投稿者只能投**其他**。

如果不會影響先加上**金融科技 FinTech** 這個選項會不會太怪呢

**Comment by uranusjr** [comment]
其實我也不知道之前的分類是怎麼訂的（可能是參考 PyCon US？），應該可以直接加沒關係。

**Comment by uranusjr** [comment]
Done in dd41443.
