### ISSUE TITLE
「稍後審查」分頁

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#368]
在 review form 裡增加「稍後審查」選項，並把標記起來的放在一個 Tab 裡 (Tab 類似下圖已經審查與未審查那個樣子)。

![](https://cloud.githubusercontent.com/assets/7709136/23329406/9d8de174-fb72-11e6-8df8-007e5c45d95c.png)

目前想的做法是在 review model 增加一個 boolean field 設定是不是 draft，然後 form 的按鈕會把這個 flag 設成 True。各分頁增加 filtering，如果是的話就放到獨立的 tab，否則放到原本的兩區。

**Comment by cropse** [comment]
嘗試了一下，不知道這樣做有沒有什麼問題？
9ca1550e11fb30d8c454e5a0a6fe24fffde420b1
2a3c98248326f022b4af1b7cbaa9fb92074e11b0

**Comment by uranusjr** [comment]
這個 project 的命名慣例不會為 boolean 加 `is_` 前綴，所以欄位叫 `draft` 比較好。其他看來沒問題。
