### ISSUE TITLE
個人審查數據計算問題

### ISSUE THREAD

**Issue by chairco** [pycontw/pycontw2016#378]
目前回報不管審查多少篇幅，都只顯示 1 在審查數據的狀態欄。
<img width="918" alt="2017-04-02 2 16 59" src="https://cloud.githubusercontent.com/assets/7709136/24581249/806f8504-174a-11e7-9967-2e1706e6ee44.png">
嘗試在程式碼內做些修改，可以參見 #377，因為改的臨時可能寫得不是很漂亮。

**Comment by uranusjr** [comment]
應該在 f7d3fc9 修復了，已 deploy。麻煩協助確認一下還有沒有問題！
