### ISSUE TITLE
firefox 講者介紹圖片無法顯示

### ISSUE THREAD

**Issue by chairco** [pycontw/pycontw2016#388]
在一般 Chrome or Safari 顯示正常。
但在 firefox 上有問題，看一下似乎是 html tag 問題
<img width="1065" alt="2017-05-08 2 42 28" src="https://cloud.githubusercontent.com/assets/7709136/25793435/00f57c6c-33ff-11e7-8c1c-91fef9f212c9.png">

**Comment by uranusjr** [comment]
我直接修 style 了，晚點 deploy。

**Comment by chairco** [comment]
感謝囉～
