### ISSUE TITLE
New UI by designer

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#39]
### signup page:
![artboard](https://cloud.githubusercontent.com/assets/902332/12006390/b85fce44-ac0f-11e5-96d5-19e69aaf113b.png)

### verify email:
(這一頁現在被 Dashboard 取代，可能不會做 )
![artboard](https://cloud.githubusercontent.com/assets/902332/12006395/f0c4a30e-ac0f-11e5-9318-3efa93aae539.png)

### login page:
![artboard](https://cloud.githubusercontent.com/assets/902332/12006400/331f68f6-ac10-11e5-8f31-fbc8e2d27b26.png)

**Comment by uranusjr** [comment]
我不喜歡 sign in（和 sign up 太接近，使用者根本搞不清楚），不過根據之前的做法，文字應該都可以做的時候再微調沒錯吧？

註冊和登入頁可能還要麻煩出一下有錯誤訊息（例如 email 已存在、兩次密碼不相符、登入帳號密碼有誤等等）的設計。

**Comment by flywindy** [comment]
我同意比較容易會看錯，可是不知道你有沒有發現最近網站好像都用 sign in，包含 Google, GitHub 都是用 sign in。

補上錯誤訊息的版本：
![artboard](https://cloud.githubusercontent.com/assets/902332/12013257/c91c39e0-ad4d-11e5-9d02-f1b94b636b35.png)

Dashboard：
![artboard](https://cloud.githubusercontent.com/assets/902332/12013275/2580e5be-ad4e-11e5-9528-6710c3c6b779.png)

Edit Profile：
![artboard](https://cloud.githubusercontent.com/assets/902332/12013284/5512150a-ad4e-11e5-8649-e2e2ee85850b.png)

**Comment by uranusjr** [comment]
在這種狀況下就不會用 sign up。Google 的登入頁和我們的很類似，可以參考。

**Comment by flywindy** [comment]
確實啊，設計師把 Sign up 改掉了。

**Comment by ccwang002** [comment]
Dashboard 投稿部份，直接導到投 Talk / Tutorial ，這樣比較簡單 xd

那需要把流程修改一下，這個是誰要做？

**Comment by flywindy** [comment]
我會做！你是說現在的設計比較簡單對嗎？

**Comment by ccwang002** [comment]
對啊，少一頁

**Comment by flywindy** [comment]
我也覺得，確實除了 UI 還有考慮到 UX

**Comment by uranusjr** [comment]
上面登入頁還是 sign up

**Comment by starwilly** [comment]
我在想 create account 那頁的 box 裡的 sign in ，移到 navbar 裡會不會比較好

**Comment by flywindy** [comment]
是說下面那一行字嗎？可是看其他網站也滿常放那的，而且這一頁沒有 navbar 啊

**Comment by starwilly** [comment]
其實應該也不用，避免 sign in / sign up 出現在距離太近的地方就好了

**Comment by uranusjr** [comment]
(開新戰場) 那個錯誤頁面如果訊息長一點應該就會寫不下，現在很多錯誤訊息都是一整句，像 *A user with that email already exists.* 這樣，要注意一下該怎麼擺。

傳統(?)上講者照片都很大（參考[去年的](https://tw.pycon.org/2015apac/en/program/24)），現在這個上傳照片比較像是 Facebook profile 那種很小一張的感覺。

**Comment by ccwang002** [comment]
補充問一下，Navbar 的下拉式選單也要設計喔，因為之後會多很多頁面。

目前可以測 About -> CoC, PyConTW; Speaking -> CfP, Talk, Tutorial, Recording Policy

**Comment by flywindy** [comment]
錯誤訊息長的狀況可以再跟設計師討論，所以可以先做。
另外，照片顯示上可以縮沒問題啊～倒是我覺得 Wording 要寫建議的圖片長寬。
@ccwang002 你們目前需要用到的最大 size 是多少？

**Comment by ccwang002** [comment]
因為圖檔會印出來，我都是用 2 x 2in (300dpi) 高估一點建議 800 x 800px 以上

**Comment by flywindy** [comment]
在 user 沒有認證的情況現在看起來是這樣（因為我把 Proposal Tab 藏起來 ）：
![screenshot-localhost 9527 2016-01-02 15-10-03](https://cloud.githubusercontent.com/assets/902332/12073639/72adffde-b163-11e5-84df-2757da7121e5.png)

@uranusjr or @ccwang002 覺得要補一段字嗎？

**Comment by ccwang002** [comment]
黃色裡面的字應該夠

**Comment by uranusjr** [comment]
我覺得要認證和填寫講者資訊之後才能發 proposal 的字可以放在下面，這樣比較明顯，也不會感覺整頁空的。上面就短短的說需要認證 email 就好。

**Comment by flywindy** [comment]
我同意 @uranusjr ，所以我是來要 Wording 的（很懶）

**Comment by ccwang002** [comment]
![Profile](https://cloud.githubusercontent.com/assets/1544283/12073665/57285596-b165-11e5-8c96-616b9079e150.png)

原本那些提示文字要加上，像是要說大頭照是正方形的；然後個人介紹不會有 formatting 就用等寬字，之前的說明要加回來。

**Comment by flywindy** [comment]
@ccwang002 Done.

**Comment by uranusjr** [comment]
1. Self Introduction 是兩個字
2. 裡面的文字不要 `vertical-align: middle` 比較好

**Comment by uranusjr** [comment]
喔我想真正的問題應該是這個 field 應該用 `textarea` 而不是 `input type="text"`…

**Comment by uranusjr** [comment]
發現一個另外的問題，現在修改資料的 form 沒辦法很快便認出哪些必須先填哪些可以先不要填（照片）。
