### ISSUE TITLE
Sponsor: TibaMe

### ISSUE THREAD

**Issue by l34marr** [pycontw/pycontw2016#390]
text for sponsors page:

TibaMe新一代學習平台，聚焦在雲端、行動、大數據、物聯網、數位金融、電商等資通訊專業領域，提供多樣化的學習方式，包括數位課程、實體課程、專案訓練與講座，近期更加入了直播教室等新型態服務。
 
TibaMe並與具30年培訓經驗的資策會、各產學界專家、領域達人、專業社群等為合作開課夥伴，希望能以最快、最新課程，搭配多樣化的學習型態，提升大家就業能力與競爭力。TibaMe為緯創旗下之教育品牌『緯育』創辦的新一代學習平台，我們相信，透過學習可以改變一個人的價值，只要願意為自己邁出第一步。

logo for sponsors page:

https://drive.google.com/file/d/0B-tFIg0TM3rYSlllTFNnbUNEalk/view?usp=sharing

**Comment by uranusjr** [comment]
有英文版文字可以上嗎，還是我試著翻譯？

**Comment by uranusjr** [comment]
我先把中文放上去了，有需要再修吧。
