### ISSUE TITLE
塞 GA Code

### ISSUE THREAD

**Issue by daikeren** [pycontw/pycontw2016#4]
好像 PR 組的人應該會有需求才對，還是直接塞個 GTM 讓 PR 組看要塞什麼 code 自己搞？

**Comment by flywindy** [comment]
@daikeren 有之前網站 GA 的權限嗎？

**Comment by daikeren** [comment]
No.  不過其實直接拿之前的 ga code 塞也行啦，我只是想說主要是要跟 PR 組提一下這件事情而已。畢竟這些是他們需要看的
如果今年跟前兩年一樣也打算下廣告的話那可能塞個 GTM 會更方便一點。

-- 
Andy Dai
Sent with Airmail

On December 25, 2015 at 12:33:56 PM, Michelle Leu (notifications@github.com) wrote:

@daikeren 有之前網站 GA 的權限嗎？

**Comment by daikeren** [comment]
@ccc-larc PR 組這部分的需求？

**Comment by ccc-larc** [comment]
收到～
有 PyConTW 用的 GA 帳號嗎？

**Comment by ccwang002** [comment]
有，問一下 @daikeren

**Comment by daikeren** [comment]
召喚 @keitheis

**Comment by keitheis** [comment]
早已把 GA admin 給了 @flywindy 囉。（早已： 昨天）
