### ISSUE TITLE
Taipei.py x PyConTW 2018 February Sprint! 二月份衝刺開發！

### ISSUE THREAD

**Issue by keitheis** [pycontw/pycontw2016#407]
### Light
Enhance documentation

  - [ ] Getting start for Web Lead
    - [ ] How to make next year
  - [ ] Getting start for Backend
  - [ ] Getting start for Frontend

### Tech Items
- [ ] Use Pipenv
- [ ] Use click or Makefile to help
- [ ] Django 2.0

**Comment by uranusjr** [comment]
[Invoke](https://github.com/pyinvoke/invoke) may be better than Click.

**Comment by keitheis** [comment]
Close as ended event.
