### ISSUE TITLE
Collapsed navbar 的 style 不太對

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#42]
![screen shot 2015-12-27 at 18 22 49](https://cloud.githubusercontent.com/assets/605277/12009871/01c0e6ce-acc7-11e5-8368-dd1508c7c3aa.png)
![screen shot 2015-12-27 at 18 23 05](https://cloud.githubusercontent.com/assets/605277/12009872/03aa6776-acc7-11e5-9189-9ef6e4264d16.png)

**Comment by starwilly** [comment]
![screen shot 2016-01-06 at 9 22 17 am](https://cloud.githubusercontent.com/assets/1353342/12134052/5863160e-b466-11e5-9f52-d28793594c83.png)
![screen shot 2016-01-06 at 9 22 07 am](https://cloud.githubusercontent.com/assets/1353342/12134056/5b7871c2-b466-11e5-901c-03b030262a1a.png)

我試著改了一下，有幾個問題：
1. 語言切換要用 html select  or bootstrap dropdown ?
2. logout button 在 mobile 的 style 有點難處理 (看起來很怪）

看是要都用 bootstrap 的 component 還是要請 designer 要出 mobile 版的 navbar，有沒有人有其它想法？

**Comment by flywindy** [comment]
HTML select 似乎不同瀏覽器會長不一樣。

**Comment by uranusjr** [comment]
長得不一樣本身不是問題，在 Firefox 上很醜是個問題。我贊成用 dropdown。

Log out 的主要問題應該是因為它是 button 而非 a tag？但應該可以用 CSS 調整吧，不確定。

**Comment by starwilly** [comment]
比較麻煩的是兩個都是 Form 的 post action , 需要額外的 js，no script 的 fall back 比較不好做。還是語言切換和 Logout 可以改成用 GET？ 

另外用 html select 的好處(?)是在手機上有 native 的 selector UI 可以選

**Comment by uranusjr** [comment]
登出連結不能用 GET，會被瀏覽器 preload。

http://stackoverflow.com/questions/3521290/logout-get-or-post

或許這兩個都可以用一樣的策略：平常用 JavaScript，no script fallback 就用現在的形式。現在的 UI 都保留，只是在 JavaScript enabled 的狀態下隱藏，用 link/dropdown 搭配 JavaScript 來 post 它們。

Native selector UI 的部分不太懂 o_o

**Comment by starwilly** [comment]
應該可以，等於是做兩種形式。

Native selector UI 其實就是這個啦，我亂取的名字
![spn3c](https://cloud.githubusercontent.com/assets/1353342/12135228/e081dea0-b473-11e5-9bb2-4e98385d8a0c.png)

**Comment by uranusjr** [comment]
噢，對耶，這確實算是個優點。

不然就兩個都做吧，然後只在 md 以上 (還是 sm? 這我不太清楚) 有 JavaScript 時用 dropdown，其他都用 select 這樣。
