### ISSUE TITLE
Keynote 頁面

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#440]
* [x] 設計
    * [x] Mobile
    * [x] Desktop
* [x] 文案
    * [x] Katie McLaughlin
    * [x] 陳昇瑋
* [x] 實作

**Comment by uranusjr** [comment]
收到陳老師的資料了，誰來幫忙填個空

**Comment by adrianliaw** [comment]
有要弄兩個語言嗎XD 還是就寫死中文就好

**Comment by uranusjr** [comment]
他都有給不是嗎

**Comment by adrianliaw** [comment]
對啊，不過這個應該要用 blocktrans 框一個英文的然後上去 transifex 貼對吧？

**Comment by adrianliaw** [comment]
喔喔沒事等等都弄都弄

**Comment by uranusjr** [comment]
(´◉◞౪◟◉)

**Comment by adrianliaw** [comment]
#447
