### ISSUE TITLE
Sprint 簡介

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#443]
有需要嗎？

**Comment by adrianliaw** [comment]
需要，不過會需要另外設計嗎？

不管怎麼樣我先加個 checklist～～

* [ ] 設計
    * [ ] Mobile
    * [ ] Desktop
* [ ] 實作

**Comment by uranusjr** [comment]
設計就抄 tutorial 頁好了

@adrianliaw 寫個文案我就做上去（有一種語言就可以了，另一邊我自行翻譯）

**Comment by uranusjr** [comment]
done?
