### ISSUE TITLE
Official CfP Jan 9

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#46]
Todo:

- [x] Speaker photo #35
- [x] Additional speaker #15 
- [x] New UI #39 
- [x] Content navbar #79
- [x] 認證 email #49
- [x] UI/UX with designer #63 
- [x] 簡化 CfP 流程 #64

有需要在 CfP 做出來的就一併列出吧。

**Comment by uranusjr** [comment]
關於 proposal 欄位… 以投稿人的角色我一直不懂 abstract 和 objective 的差異。一個好的摘要本身似乎就應該說明 target audience 與演講的內容，至少我寫論文的時候是被這樣教，因為這樣才能讓會眾（讀者）知道要不要參加（閱讀）你的作品。所以這兩個欄位看上去似乎很重複。

或許實際上的差異是 abstract 會被印出來，其他欄位是給 reviewers 看的？如果是這樣可能需要標註一下，其他欄位也是。

**Comment by ccwang002** [comment]
我大概會保留 abstract 和 objective。objective 專門寫合適的聽眾、以及聽眾能得到什麼。abstract 基本上沒有限制，字數內投稿人愛怎麼寫就怎麼寫。另一個差別 objective 不會公開，有些講者可能會想把一些內容藏在這。

你說的沒錯啦，但就前幾次的經驗，還是蠻多投稿 abstract 寫得很隨便。然後我應該會用 objective 來判斷講題的難易度。

在投稿說明裡面有寫 https://pycontw.krdai.info/2016/zh-hant/speaking/talk/ 不過我想應該是沒有人會去看，我還是加在欄位說明裡好了。

今年如果實驗效果很差就再拿掉吧…
