### ISSUE TITLE
PyCon TW 2017 網站的議程表變成今年的啦

### ISSUE THREAD

**Issue by adrianliaw** [pycontw/pycontw2016#465]
請看：https://tw.pycon.org/2017/zh-hant/events/schedule/

Reference: Dealing with the same issue in 2016: https://github.com/pycontw/pycontw2016/commit/10890386a2172d85e32a53b3c4e08d6399dfd4e4

**Comment by uranusjr** [comment]
Done 59a94b307a86

**Comment by adrianliaw** [comment]
@uranusjr 我們是不是應該把 `Schedule` 也變成 `ConferenceRelated`，這樣之後就不用每年改

**Comment by uranusjr** [comment]
欸好有道理喔我怎麼之前都沒想到。PR 交給你了。
