### ISSUE TITLE
Talk detail 頁面需要顯示簡報連結

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#476]
https://t.me/pycontw2018/307

**Comment by david30907d** [comment]
您好 我的簡報好像沒出現
https://tw.pycon.org/2018/zh-hant/events/talk/593232781107003552/

這是我的簡報檔：https://docs.google.com/presentation/d/1ZNtpuWycubxKaz9oskyFemmlqFaNW6cYiIW7Ig0dk_0/edit?usp=sharing
抱歉打擾了
