### ISSUE TITLE
重設密碼

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#48]
總是要有這個功能

**Comment by flywindy** [comment]
忘記密碼咧 XD

**Comment by ccwang002** [comment]
新 UI 就多放一個 Account tab 或跟 Profile tab 放一起處理帳密吧 #39

**Comment by uranusjr** [comment]
這個就是忘記密碼啊，是「重設」不是「修改」。

**Comment by flywindy** [comment]
重設跟修改就字面上沒有什麼不同啊
忘記密碼的流程通常是：
- 提供 email 寄送一組新的亂數密碼
- 用亂數密碼登入
- 在 Profile 或是 Account 頁面重新設定密碼

**Comment by uranusjr** [comment]
@ccwang002 你關錯 issue 了～～～～
