### ISSUE TITLE
認證 email 的內容

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#49]
之前講的好像沒下文，但這也是得在 CfP 之前出現吧。

是誰要做？

**Comment by ccwang002** [comment]
參考 https://github.com/pycontw/pycontw2016/issues/6#issuecomment-166890826 我來做吧

**Comment by uranusjr** [comment]
忘記密碼 #48 的信也需要寫一下。這個還沒有 template，就先把文案放到這裡或 Slack，我做的時候再拿去用。

**Comment by ccwang002** [comment]
忘記密碼的 template 放在 `/src/templates/registration/password_reset_email.txt`

Review 吧
