### ISSUE TITLE
Facebook open graph 相關 tag

### ISSUE THREAD

**Issue by daikeren** [pycontw/pycontw2016#5]
這應該也要請 PR 組的人來處理一下？

**Comment by flywindy** [comment]
Reference: https://developers.facebook.com/docs/sharing/webmasters#markup

**Comment by daikeren** [comment]
@ccc-larc 可以幫忙一下嗎？

**Comment by ccc-larc** [comment]
ok

**Comment by ccc-larc** [comment]
FB 分享用圖片 (尺寸：1200 x 630)
- [ ] 首頁
- [ ] CfP

**Comment by flywindy** [comment]
CfP 具體來講是什麼時候用的？

**Comment by ccc-larc** [comment]
看看是否會分享 CfP 的訊息到 Facebook
如果會，除了標題文字外，還會出現圖片

**Comment by flywindy** [comment]
了解。可以分開描述一下這兩種圖裡面還需要加上什麼元素或文字嗎？上次好像有人說首頁的圖要放上 PyCon TW 2016 日期。

**Comment by flywindy** [comment]
@ccc-larc 就剛剛的示範來看，因為下面也會有 “Call for Proposals” 的字和描述，我覺得圖片可以跟首頁分享的圖共用耶？

**Comment by ccc-larc** [comment]
1. 後來好像要讓設計師自由發揮？
2. CfP 應該可以跟首頁用同一張圖

**Comment by flywindy** [comment]
og:image 要用絕對路徑，@daikeren 麻煩你改一下。

**Comment by flywindy** [comment]
沒有 `og:description` 目前長這樣：
<img width="489" alt="screen shot 2016-01-09 at 9 22 35 pm" src="https://cloud.githubusercontent.com/assets/902332/12216294/693a694c-b717-11e5-9030-595e718018c2.png">

中文：
<img width="479" alt="screen shot 2016-01-09 at 9 22 01 pm" src="https://cloud.githubusercontent.com/assets/902332/12216295/71250eaa-b717-11e5-95f7-54f647b2c7b9.png">
