### ISSUE TITLE
Templates 套 Bootstrap 

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#6]
主要修改：
```
templates
├── _includes
│   └── nav.html
├── proposals
│   ├── talk_proposal_create.html
│   └── talk_proposal_update.html
├── registration
│   ├── login.html
│   └── signup.html
└── users
    ├── user_dashboard.html
    └── user_profile_update.html
```
Reference:
- http://getbootstrap.com/
- [django-crispy-forms](https://github.com/maraujop/django-crispy-forms/)
- [Mockup](https://docs.google.com/document/d/1dThOGyjSU6rIE_b9oYe7Vun1Lcy2IuKfGiCVgNSoN7E/edit)

**Comment by flywindy** [comment]
新增頁面：
```
templates
├── proposals
│   ├── create_proposal_choice.html
│   ├── tutorial_proposal_create.html
│   └── tutorial_proposal_update.html
└── registration
    └──  activation_email.html
```

**Comment by ccwang002** [comment]
我把流程圖畫好了，這樣 ok 嗎？ cc @flywindy 

![Call for Proposal Workflow](https://cloud.githubusercontent.com/assets/1544283/11974867/3369d7f2-a9a3-11e5-99e1-681fbcb8a4b2.png)

**Comment by flywindy** [comment]
@ccwang002 
Tutorial 那一塊還沒加上？
- tutorial_proposal_create.html
- tutorial_proposal_update.html

**Comment by ccwang002** [comment]
Tutorial 跟 talk 是一樣的意思，把 talk 做好再複制過去就好

**Comment by uranusjr** [comment]
提醒一下 `activation_email.html` 是要當作帳號認證信寄出的，所以不能像其他 templates 那樣繼承，需要是一個完整的 HTML，然後所有的外部檔案都要用完整路徑才行喔。

然後還有一個上面沒提到的，`activation_email.txt` 是認證信的純文字版，這個也要做（應該包含 HTML 版的所有訊息，只是是純文字）。

**Comment by daikeren** [comment]
省事一點認證信做純文字就好了吧？html 有點煩...

**Comment by flywindy** [comment]
`activation_email.txt` 我覺得存文字就好了耶！如果要加 HTML 就變成 EDM 了。另外文字部分應該沒那麼簡單吧？Wording 是要呼叫 PR 組嗎？

**Comment by ccwang002** [comment]
那只做純文字吧，文字的部份我覺得現在的版本就夠了，相信大家都懂認證信，不用花太多時間。

**Comment by uranusjr** [comment]
現在的文字我是抱著亂寫才不會有人把它當真的心態做的耶 XDDDD

**Comment by flywindy** [comment]
@uranusjr 我知道啊！所以我現在很認真的問說 Wording 是問 @ccwang002 還是找 PR組 ?

**Comment by daikeren** [comment]
@ccwang002 根本就沒認真看過 wording 吧！！！！

**Comment by flywindy** [comment]
分享一下我最近收到的類似信件（純文字）

Title: **Complete your account registration**

Dear Michelle,

Thank you for creating your XXXX Account.

To complete your registration, click the link below:
[Confirm your account]()

Yours truly,
XXX Sales Team

**Comment by uranusjr** [comment]
click the link  ← 有這個就不是純文字了至少是 RTF 欸

**Comment by flywindy** [comment]
https://github.com/pennersr/django-allauth/tree/master/allauth/templates/account/email
我覺得直接 Show link 就好了

**Comment by flywindy** [comment]
另外，我沒看到 Forgot password 的頁面？

**Comment by uranusjr** [comment]
PyCon US 的 email 只是提示，不是要求認證喔，他們是 email 註冊了就直接過，只是寄一封信確定你沒亂填。

忘記密碼的頁面根本沒做，因為好像也不會那麼常用到，想說優先權可以低一點…

**Comment by ccwang002** [comment]
原來大家都這麼仔細看啊 xd 直接貼連結就好了。

對了，template 需要放 message 喔，我看 TP 有用。

**Comment by flywindy** [comment]
@uranusjr 為什麼測試要測到前端的東西啊 @.@

assert len(submit_buttons) == 2
E       assert 1 == 2
E        +  where 1 = len([<Element button at 0x10d07aae8>])

這樣改前端不是還要改測試嗎 T.T

**Comment by flywindy** [comment]
我剛重新測試了一次，覺得 Signup 完直接到首頁怪怪的，通常至少會去另外一頁，然後說請去收信吧？
我覺得可以導到 Dashboard，如果 inactive 的話就顯示那一段文字提示。
然後最好可以有一個按鈕是 `resend email` 之類的？

**Comment by uranusjr** [comment]
我有 post 一個 [success message](https://github.com/pycontw/pycontw2016/blob/master/src/users/views.py#L27)，請在 template 裡（建議 `base.html`）[把它寫出來](https://docs.djangoproject.com/en/1.9/ref/contrib/messages/#django.contrib.messages.get_messages)。

**Comment by flywindy** [comment]
@uranusjr 你目前的 message 都是用在使用者後台對嗎？ 我應該不會寫在 `base.html`，我覺得出現在首頁有點怪。

**Comment by uranusjr** [comment]
它應該要出現在每一頁啊，就是在某一頁 submit 一個 form 進入下一頁時會有個 overlay 顯示訊息。現在你建立/修改/撤回/重開 proposal 的時候也會有。

**Comment by flywindy** [comment]
我明白你的意思，我只是說後台跟前台( static files ) 要分開。message 會出現在後台的每一頁，所以我也覺得註冊完不用回首頁，可以留在同一頁就好。

**Comment by uranusjr** [comment]
OK 那就看要怎麼改了，交給你們。

註冊完如果回同一頁會是註冊頁，好像不太對。不然導到登入頁如何？

**Comment by flywindy** [comment]
噢～好像滿合理的。
