### ISSUE TITLE
PyCon TW 個人贊助頁面

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#61]
Reference: https://pycon.jp/2015/ja/sponsors/patrons/
<img width="844" alt="skitch" src="https://cloud.githubusercontent.com/assets/902332/12078052/c6411a44-b23c-11e5-96fa-fe04b4a118d4.png">

KKTIX 報名頁面：http://pycontw.kktix.cc/events/pycontw2016patron
- Banner: We recommend you use image of size bigger than 1200x630, at most 2MB. If you do not upload, we will use default image.

**Comment by uranusjr** [comment]
我想了一下，這個應該就是得定期從 KKTIX 爬資料回來了吧。後台可以輸出報表然後再用一個 management command 來匯入嗎？

我想這部分應該不需要用到資料庫，直接把公開資料輸出成一個 CSV 或 JSON 之類的當成 static file 就好。

另外 KKTIX 上的 form 似乎也應該標註 banner 的說明文字？

**Comment by flywindy** [comment]
最後一句什麼意思？

**Comment by uranusjr** [comment]
你上面的最後一段應該是在說明 patron 提供的圖片尺寸？如果是這樣的話，這段話應該出現在 KKTIX 的報名 form 裡，不然從那邊報名的人不會知道要傳符合這個標準的圖片。

**Comment by flywindy** [comment]
抱歉，那一句是要給設計師的，是指 KKTIX 頁面 Banner 圖片的尺寸。

**Comment by uranusjr** [comment]
OK

**Comment by ccwang002** [comment]
我先列一下要做的：

- [ ] 確認 KKTIX 各欄位的格式與說明無誤
- [ ] Patron 頁面設計
- [ ] 與 KKTIX 資料整合

**Comment by flywindy** [comment]
[KKTIX 個人贊助頁](http://pycontw.kktix.cc/events/pycontw2016patron)

**Comment by flywindy** [comment]
設計：
![artboard](https://cloud.githubusercontent.com/assets/902332/14312760/4f5bb8b6-fc20-11e5-9dbe-9068a5920b8e.png)

**Comment by uranusjr** [comment]
我想問一下現在有從 KKTIX export 的資料嗎？如果有格式的話我就可以把 UI 做出來，這樣之前提到個人贊助資訊不明顯的問題也可以部分解決。現在離 conference 也只剩一個月多一點，再不讓大家知道，這個東西大概也沒什麼用了。

**Comment by flywindy** [comment]
@starwilly  好像做了一半，我問問看他。
是說本來其實只有一個人，所以才想說先在暫緩啊

**Comment by flywindy** [comment]
等議程表做出來就來做吧

**Comment by uranusjr** [comment]
其實主要是現在真的露出度太低，都有人在抱怨了⋯⋯

重點還是要有個頁面（然後可能在首頁放個連結），有沒有顯示人在上面倒是其次。

**Comment by flywindy** [comment]
嗯，但現在早鳥票沒賣完，我想就 Nav 多加一個連結吧！

**Comment by ccwang002** [comment]
在 nav 加個連結我可以做（舉手）

**Comment by flywindy** [comment]
今日開會結果：
把個人贊助放在特殊贊助下面

**Comment by uranusjr** [comment]
有 update 嗎？
