### ISSUE TITLE
edit-btn 的 hover 與 active 狀態需要修正

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#66]
Normal:
![screen shot 2016-01-04 at 22 51 48](https://cloud.githubusercontent.com/assets/605277/12092072/e02566a0-b335-11e5-8204-2ede864d400b.png)

Hover:
![screen shot 2016-01-04 at 22 51 53](https://cloud.githubusercontent.com/assets/605277/12092086/edd5a5f8-b335-11e5-883d-11efe0943717.png)

其他還有不少地方也用到這個按鈕，例如投稿 proposal 的 submit 鈕與編輯個人資料的取消鈕，狀況應該都一樣。

**Comment by flywindy** [comment]
這部分我跟設計師提過了，所有按鈕和 Sidebar 的選項都會做 Hover。

**Comment by flywindy** [comment]
![contributionsystem_userdashboard_hoverstatus](https://cloud.githubusercontent.com/assets/902332/12173168/3371cfe0-b590-11e5-8f86-52731e5ea3e6.png)
