### ISSUE TITLE
Dashboard home page

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#80]
1. 剛註冊完還沒填寫 Profile：
![artboard](https://cloud.githubusercontent.com/assets/902332/12174790/b39ae5cc-b599-11e5-91a8-8feb61a16a79.png)

2. No proposal：
![artboard](https://cloud.githubusercontent.com/assets/902332/12174820/e0bad346-b599-11e5-8258-31ee88aabad3.png)

3. Withdraw/Reactive：
![artboard](https://cloud.githubusercontent.com/assets/902332/12174860/0d0ed244-b59a-11e5-894a-17ac1fc5b908.png)

**Comment by flywindy** [comment]
這一塊不影響功能，只是 UX 會比較好，我打算交給 @yaohappy 幫忙～

**Comment by uranusjr** [comment]
需要把 `user_dashboard` view 的前兩行刪掉，不然第一頁無法顯示（會被重導向到 `user_profile_update`）。應該是不會動到其他功能。
