### ISSUE TITLE
Form non_field_errors styles

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#82]
Edit proposal 的 form.non_field_errors 可能比較好測試。

**Comment by uranusjr** [comment]
我比對了一下，目前整個站上應該是完全沒有 form 在正常情況下會用到 `non_field_errors`。如果要測試可以手動在隨便一個 form（推薦 `UserProfileUpdateForm`，畢竟目前也只有它是手動 render）的 `save` 裡面 raise `forms.ValidationError('message...')` 來看會比較快。

（不正常的情況包括有人沒填好 speaker profile 就不知為何找到連結能夠 create proposal 之類的。）
