### ISSUE TITLE
Add "trimmed" to blocktrans tags

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycontw2016#85]
才不會在翻譯檔裡看到一堆 tab…

今天才知道有這個東西。

https://docs.djangoproject.com/en/1.9/topics/i18n/translation/#blocktrans-template-tag

**Comment by flywindy** [comment]
太好了！你今年的 talk #30 又可以增加一個項目 :+1:

**Comment by keitheis** [comment]
賀喜少爺 :coffee:
