### ISSUE TITLE
Navbar 文字翻譯

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#89]
目前 navbar 還沒翻譯，然後 https://tw.pycon.org/2016/zh-hant/accounts/signup/
下面有個 `已經有帳號了？`**`請`**`登入`
那個請是不是不要翻，不然好像跑掉了。英文沒這個問題

**Comment by ccwang002** [comment]
Done. Please check.

**Comment by ccwang002** [comment]
先關掉好了
