### ISSUE TITLE
Speaker photo upload button

### ISSUE THREAD

**Issue by flywindy** [pycontw/pycontw2016#90]
似乎是用有點暴力的方法寫的（把 input 透明度設為 0），所以有可能會出問題。
另外 @daikeren 覺得點選完上傳後應該要顯示點什麼（之前會顯示檔案名稱）

**Comment by ccwang002** [comment]
我也覺得要顯示名稱，然後現在還不會判斷傳照片的尺寸？例如：

- 檢查 > 800x800 px
- 檢查比例是否 1:1

**Comment by uranusjr** [comment]
圖片尺寸目前沒有檢查，有需要的話我現在可以開始做。

如果是要讓使用者知道有上傳成功，或許可以偵測如果上傳的圖片有改就給一個 success message 表示圖片有更新？

**Comment by ccwang002** [comment]
剛剛試完投稿，應該就圖片這邊可以改一下，改吧 xd
