### ISSUE TITLE
About / PyCon TW 2016

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#91]
沒內容

**Comment by ccc-larc** [comment]
請問希望放哪些內容？
首頁似乎有介紹 PyCon Taiwan 了

**Comment by ccwang002** [comment]
希望能比較詳細地介紹 PyCon Taiwan。例如幾年成立，演進等等。
另一方面希望能對各個在地社群有比較多的介紹，可能可以把 logo 放上來。

去年 mimi 有做一張投影片把 logo 畫在地圖上，概念上感覺還不錯，可以參考。
![](https://blog.liang2.tw/2015Talk-Chinese-Search/pics/taiwan_py_community.png)

**Comment by uranusjr** [comment]
話說剛剛看了一下 geekpy.org 好像死了…

**Comment by l34marr** [comment]
We can decide who to compile the visual work later. Before that, we need logo raw materials ready. I've look into Google Drive (pycontw2015 / Printing & Visual) but see no materials yet. I propose logo raw materials be collected first into pycontw2016 / Web / Design / Assets. @ccc-larc would you help this? I will help figure out who to implement the visual work.

**Comment by ccc-larc** [comment]
收集社群 logo 到 Google Drive：`pycontw2016 / Web / Design / Assets / Local`

    DjangoGirls_200x70.png
    HualienPy_790x507.jpeg
    PyHUG_400x420.jpeg
    PyLadies_960x960.jpeg
    TaichungPy_2252x2096.jpeg
    TainanPy_180x163.jpeg
    TaipeiPy_204x84.png
    TaoyuanPy_550x220.jpg

**Comment by ccc-larc** [comment]
收集 PyConTW/APAC 歷年 logo 到 Google Drive：`pycontw2016 / Web / Design / Assets / PyConTW & APAC`

    PyConAPAC2014_740x639.png
    PyConAPAC2015_845x279.png
    PyConTW2012_699x262.png
    PyConTW2013_800x368.png

**Comment by ccc-larc** [comment]
目前 About/PyConTW 中文部分差不多定稿了，或許可以翻譯成英文，讓贊助組運用？

**Comment by ccwang002** [comment]
Hi @ccc-larc 我先關掉這個 issue 然後再另開一頁討論英文翻譯的事項。有人要跳坑嗎？
