### ISSUE TITLE
Keynote Speaker 介紹

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#92]
- [x] about/keynote speakers 英文內容
- [x] about/keynote speakers 中文內容
- [x] keynote 照片

**Comment by flywindy** [comment]
我以為這個 issue 是表示 content 的準備程度？

**Comment by ccwang002** [comment]
喔對…我把 label 拿掉

**Comment by flywindy** [comment]
嗯？我的意思是看起來 Keynote Speaker 介紹還不完整？

**Comment by ccwang002** [comment]
啊…對，但我想先把那個 PR merge 掉，這樣設計師有內容可以看，我們組員也能了解狀況

**Comment by flywindy** [comment]
嗯，我懂，剛 merged，想說這個 issue 還是要留下來。

**Comment by flywindy** [comment]
設計來了：
![artboard](https://cloud.githubusercontent.com/assets/902332/12666444/e93d0ba4-c67b-11e5-8618-30339c007fe4.png)
@ccwang002 @uranusjr @starwilly @daikeren 覺得如何？
我個人覺得圓框疑似有點粗 XD

**Comment by ccwang002** [comment]
我覺得照片可以大一點，但整體上 ok 。

**Comment by uranusjr** [comment]
同意問題應該是照片太小，如果是大圖那個圓框應該就 OK。

內文的字型一樣可能需要調整 (see https://github.com/pycontw/pycontw2016/issues/94#issuecomment-176565750)

**Comment by flywindy** [comment]
圖片已改成 124px，另外有這一頁的情況，首頁還要放 keynote 嗎？

**Comment by ccwang002** [comment]
先不用吧
