### ISSUE TITLE
Sponsor 相關的內容上線

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#94]
- Sponsor 介紹（從 sponsor 組拿）
- 贊助商管理 model?

**Comment by flywindy** [comment]
設計：
![artboard](https://cloud.githubusercontent.com/assets/902332/12666476/49a5d5fc-c67c-11e5-9321-80d50c4845c7.png)
一樣請大家給予意見 :)

**Comment by uranusjr** [comment]
字太小又太細根本無法讀，目前所有設計幾乎都有這問題（雖然贊助商的內容應該也不會有人看）。根據之前調 content pages 的經驗，內文可能要用 weight 400 搭配 size 16px，或者 weight 300 搭配 size 18px 比較合適。

可能要考慮如果下面廣告詞太長要怎麼處理（`text-overflow : ellipsis` 之類的）。

另外中英文字型很不統一，看縮圖就很明顯區塊的濃淡差異很大。不過這個應該之後可以用 webfont 解決。可是這個東西有進度嗎？

**Comment by l34marr** [comment]
For the cases of long text, is scrollbar helpful?
Anyway, I think http://tw.pycon.org/2014apac/en/sponsors is a good and simple demo, to list sponsors.

**Comment by flywindy** [comment]
新版本 Sponsor 頁面：
![artboard](https://cloud.githubusercontent.com/assets/902332/14312823/86c14cc6-fc20-11e5-819c-c010b226689d.png)

**Comment by flywindy** [comment]
Sponsor 側邊欄設計：
![artboard](https://cloud.githubusercontent.com/assets/902332/14312842/a1251138-fc20-11e5-9bbc-4d074fd29522.png)

**Comment by uranusjr** [comment]
所以之後是每一頁都要改成有贊助商 sidebar 嗎？

**Comment by flywindy** [comment]
贊助商頁面都不需要，然後議程那一頁...有可能會放不下。

**Comment by uranusjr** [comment]
所以是大部分都要？另外 BoF 的新設計應該也沒辦法放。

**Comment by flywindy** [comment]
嗯... 這邊我可以再跟設計師確認一下。
Sponsor 你有打算寫 Models 嗎？(當初有開這個 app 就是...)

**Comment by agogomei01** [comment]
Hi Michelle,

如果，有些版面會放那如果只放白金級跟金級廠商的logo.
目前，白金級一個是IBM.

預計，可能會再增加一個白金或兩個金級。

不確定，這樣子會讓大家比較方便嗎？

BR,

Ning Chen
2016年4月9日 上午1:13於 "Michelle Leu" <notifications@github.com>寫道：

嗯... 這邊我可以再跟設計師確認一下。
Sponsor 你有打算寫 Models 嗎？(當初有開這個 app 就是...)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/pycontw/pycontw2016/issues/94#issuecomment-207521416>

**Comment by flywindy** [comment]
Hi Ning,

大部分版面會放，少部分版面不會放的原因是因為設計裡面擺不下 Sidebar。
跟只放白金級和金級沒有關係。

但如果你 Sidebar 只放白金級和金級當然可以，這樣也可以讓白金級和金級有尊榮感。

**Comment by agogomei01** [comment]
Hi Michelle,

我懂你的意思。

我是偏向只放白金級跟金級客戶，有尊容感。

BR

Ning Chen
2016年4月9日 下午3:49於 "Michelle Leu" <notifications@github.com>寫道：

**Comment by flywindy** [comment]
白金級 設計：
![screen shot 2016-04-27 at 6 36 53 pm](https://cloud.githubusercontent.com/assets/902332/14849894/2e201960-0ca8-11e6-8cf8-d325bfb30912.png)

充滿尊榮感！

**Comment by uranusjr** [comment]
ping

**Comment by uranusjr** [comment]
Closing since we’re freezing features for 2016.
