### ISSUE TITLE
中文 webfont

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#98]
先說感想：我覺得字太細了，可以做 webfont，金額也不高（justfont 1M page views ~2500 NTD）

目前在 Windows 10 Edge 上長這樣：

![screen shot 2016-01-12 at 23 35 32](https://cloud.githubusercontent.com/assets/1544283/12267965/b0790b0e-b985-11e5-91fa-8d83e556b095.png)
![screen shot 2016-01-12 at 23 35 07](https://cloud.githubusercontent.com/assets/1544283/12267966/b140e08e-b985-11e5-995a-2587ee1ac1ab.png)
![screen shot 2016-01-12 at 23 36 01](https://cloud.githubusercontent.com/assets/1544283/12267967/b32ab294-b985-11e5-8942-c030e99efb67.png)
![screen shot 2016-01-12 at 23 38 20](https://cloud.githubusercontent.com/assets/1544283/12267971/b479e9a8-b985-11e5-92d7-f97a69289b46.png)

另外 console 噴了一些 caching XHR 相關的 404，不是很懂，一起放這邊
![screen shot 2016-01-12 at 23 37 40](https://cloud.githubusercontent.com/assets/1544283/12268034/02e61972-b986-11e5-9144-6e83270d46de.png)

**Comment by ccwang002** [comment]
IE11
![screen shot 2016-01-12 at 23 44 15](https://cloud.githubusercontent.com/assets/1544283/12268146/7a89fe58-b986-11e5-9690-6bfdc3f6ec26.png)

**Comment by uranusjr** [comment]
那個 XHR 錯誤怎麼很像是想讀 non-minified 的檔案… 感覺是 Django Compressor 的問題。不太懂。

**Comment by uranusjr** [comment]
另外字型的部分我在本機試了 Source Han Sans 應該合用，Light 和 Regular 感覺和 Roboto 算是合。而且 justfont 好像有免費的可以用。

**Comment by daikeren** [comment]
XHR 404 應該是 edge 不知為何自己要去找 sourcemap 裡面的檔案，可能想偷偷存些東西...

**Comment by flywindy** [comment]
內文顏色已經改了。然後免費版的 justfont 有廣告而且 Http only。

**Comment by ccwang002** [comment]
你們要測的話，我可以出借我的 Business Plan，我自己用不了這麼多。

有需要就請錢報預算吧。

**Comment by flywindy** [comment]
好啊，我需要先測試，麻煩給我帳號吧

**Comment by ccwang002** [comment]
Retry using [Google webfont](https://www.google.com/fonts/earlyaccess), which ships Noto Sans.

See also: <http://tt5.org/google-fonts-%E6%8F%90%E4%BE%9B%E4%BA%94%E7%A8%AE%E4%B8%AD%E6%96%87-wenfont%EF%BC%8C%E6%97%A9%E8%B5%B7%E7%9A%84%E9%B3%A5%E5%85%92%E6%9C%89%E7%9A%84%E7%8E%A9/>
